//!function="true",{/**
//"use strict";loaded_1_6(function(_){var wi/ndow=this;/**
_.m("d6FVZd");

_.p();
//**_.m("yb08jf");/**
var Ngd=function(){var a=this;this.Aa=[];this.Fa=1;var b=window;this.oa=void 0===b.ResizeObserver?void 0:new b.ResizeObserver(function(c){Mgd(a,c)})},Mgd;Ngd.prototype.addCallback=function(a,b){var c=this,d=this.Fa++;if(void 0===this.oa)return d;a=a instanceof _.zq?a.toArray():[a];this.Aa.push({key:d,elements:a,callback:b});a.forEach(function(e){c.oa.observe(e)});return d};
_.Ogd=function(a,b){if(void 0!==a.oa){var c=a.Aa.filter(function(d){return d.key===b}).flatMap(function(d){return d.elements});a.Aa=a.Aa.filter(function(d){return d.key!==b});c.filter(function(d){return!a.Aa.flatMap(function(e){return e.elements}).includes(d)}).forEach(function(d){a.oa.unobserve(d)})}};Ngd.prototype.pause=function(){void 0!==this.oa&&this.oa.disconnect()};Ngd.prototype.resume=function(){var a=this;void 0!==this.oa&&this.Aa.flatMap(function(b){return b.elements}).forEach(function(b){a.oa.observe(b)})};
//**Mgd=function(a,b){a.Aa.forEach(function(c){var d=b.filter(function(e){return c.elements.includes(e.target)});0<d.length&&c.callback(d)})};_.MH=function(a){_.kq.call(this,a.Oa);this.oa=new Ngd};_.D(_.MH,_.kq);_.MH.Va=_.kq.Va;_.MH.Ka=function(){return{}};_.MH.prototype.addCallback=function(a,b){return this.oa.addCallback(a,b)};_.MH.prototype.pause=function(){this.oa.pause()};_.MH.prototype.resume=function(){this.oa.resume()};_.mq(_.edb,_.MH);
_.p();
_.m("KcokUb");
_.pKb=new _.yh(_.qib);
_.p();
_.m("NoECLb");
var E0e=function(a){_.kq.call(this,a.Oa);this.Lt=a.service.Lt};_.D(E0e,_.kq);E0e.Va=_.kq.Va;E0e.Ka=function(){return{service:{Lt:_.pKb}}};_.h=E0e.prototype;_.h.Tb=function(){return this.Lt.Tb()};_.h.ZG=function(){return this.Lt.ZG()};_.h.lj=function(a){return this.Lt.lj(a)};_.h.Gk=function(a){return this.Lt.Gk(a)};_.h.xK=function(a){return this.Lt.xK(a)};_.mq(_.rib,E0e);
_.p();
_.m("hypYI");
_.YEm=function(a){_.kq.call(this,a.Oa);this.window=a.service.window.get();this.document=a.service.window.zd()};_.D(_.YEm,_.kq);_.YEm.Va=_.kq.Va;_.YEm.Ka=function(){return{service:{window:_.kv}}};_.YEm.prototype.oa=function(){return this.document.documentElement.clientWidth/this.window.innerWidth};_.mq(_.cfb,_.YEm);
_.p();
var F6g;F6g=_.$f().zd().documentElement;_.E6g=F6g.requestFullscreen?"fullscreenchange":F6g.webkitRequestFullscreen?"webkitfullscreenchange":F6g.mozRequestFullScreen?"mozfullscreenchange":F6g.msRequestFullscreen?"MSFullscreenChange":"fullscreenchange";_.G6g=function(a){a=a?a.zd():_.$f().zd();var b=a.body;return!!(b.webkitRequestFullscreen&&a.webkitFullscreenEnabled||b.mozRequestFullScreen&&a.mozFullScreenEnabled||b.msRequestFullscreen&&a.msFullscreenEnabled||b.requestFullscreen&&a.fullscreenEnabled)};
_.H6g=function(a,b){if(a.requestFullscreen)return a.requestFullscreen(b);if(a.webkitRequestFullscreen)return a.webkitRequestFullscreen();if(a.mozRequestFullScreen)return a.mozRequestFullScreen();if(a.msRequestFullscreen)return a.msRequestFullscreen()};_.I6g=function(a){a=a?a.zd():_.$f().zd();a.exitFullscreen?a.exitFullscreen():a.webkitCancelFullScreen?a.webkitCancelFullScreen():a.mozCancelFullScreen?a.mozCancelFullScreen():a.msExitFullscreen&&a.msExitFullscreen()};
_.J6g=function(a){a=a?a.zd():_.$f().zd();return!!(a.webkitIsFullScreen||a.mozFullScreen||a.msFullscreenElement||a.fullscreenElement)};
//_.bFm=function(a,b){return{XR:a,B0c:b}};_.cFm=_.T("F8aUwf");_.dFm=_.T("cFUGcd");_.eFm=_.T("Qk96Ab");_.fFm=_.T("ojL58");_.gFm=_.T("DSlWvf");_.hFm=_.T("cPKAwe");_.iFm=_.T("znUj3");_.jFm=_.T("KZOHMb");_.kFm=_.T("TvgVS");_.lFm=_.T("pwISFb");_.mFm=_.T("jQntwf");_.nFm=_.T("DnYN3d");_.oFm=_.T("ICrPLb");_.pFm=_.T("iPWSJb");_.qFm=_.T("ZVbNQe");_.rFm=_.T("f2KIuf");_.sFm=_.T("D8UFDb");_.tFm=_.T("x5gMP");
_.m("yGkNuf");
var yFm,FFm,AFm;
/**_.L7=function(a){_.kq.call(this,a.Oa);var b=this;this.Za=0;this.Cb=null;this.Qa=void 0;this.Xg=this.Ia=this.yc=this.oa=this.Ua=this.Na=this.tb=null;this.Xc=function(){var c=_.uFm(b);c&&(b.oa.style.top=c.getBoundingClientRect().top+"px")};this.j0=function(){if(b.isInitialized()){var c=_.uFm(b);if(c){var d;if(null!=(d=_.vFm(b))&&_.F(d,2)){if(_.wFm()){d=_.uFm(b).getBoundingClientRect().width;var e=b.Nm.Aa().size.height,f=_.xFm(b);d=Math.round(d/f);d>e&&(d=e);var g;null==(g=yFm(b))||g.style.setProperty("border-radius","16px");
 * /*c.style.borderRadius="16px";1>=f&&(d=Math.min(Math.round(.67*e),950));c.style.height=d+"px";1>=f&&(c.style.width=d*f+"px");b.oa.style.height=d+"px";b.oa.style.width=d*f+"px";b.oa.style.top=c.getBoundingClientRect().top+"px";b.oa.style.left=c.getBoundingClientRect().left+"px"}else{var k=b.vr()?b.xc:b.Sb,l=(b.vr()?b.Sb:b.xc)-52;g=b.vr();d=!g&&1>=_.xFm(b)?1.778:_.xFm(b);k=Math.round(k/d);k>l&&(k=l);g||(k*=.9);l=k;d*=k;c.style.height=l+"px";c.style.width=d+"px";if(c=_.uFm(b))g?(b.oa.style.removeProperty("clip-path"),
 * null==(e=yFm(b))||e.style.removeProperty("border-radius"),c.style.removeProperty("border-radius")):(null==(f=yFm(b))||f.style.setProperty("border-radius","16px"),c.style.borderRadius="16px");b.oa.style.left="50%";b.oa.style.transform="translate(-50%, 0)";b.oa.style.height=l+"px";b.oa.style.width=d+"px"}b.broadcast(_.qFm)}}}};this.Ya=function(){b.j0();b.vr()?(b.broadcast(_.tFm,1),_.zFm()&&_.G6g(b.Ma)&&_.J6g(b.Ma)&&(b.broadcast(_.sFm),_.I6g(b.Ma))):(b.broadcast(_.tFm,2),!_.wFm()&&_.zFm()&&_.G6g(b.Ma)&&
 * !_.J6g(b.Ma)&&(b.broadcast(_.rFm),b.Ia&&AFm(b.Ia)));_.BFm()&&b.broadcast(_.lFm);CFm(b)};this.Nm=a.service.Nm;this.Aa=a.service.window.get();this.Ma=new _.oj(this.Aa.document);this.Fa=this.Aa.matchMedia("(orientation: portrait)");this.OV=a.service.OV;this.xc=Math.min(this.Aa.innerWidth,this.Aa.innerHeight);this.Sb=Math.max(this.Aa.innerWidth,this.Aa.innerHeight);this.Qb=function(){"hidden"===document.visibilityState&&b.broadcast(_.oFm)}};_.D(_.L7,_.kq);_.L7.Va=_.kq.Va;
 * _.L7.Ka=function(){return{service:{OV:_.MH,Nm:_.Gv,window:_.kv}}};_.zFm=function(){return!1};_.wFm=function(){return!1};_.BFm=function(){return!1};yFm=function(a){!a.Ia&&a.oa&&(a.Ia=a.oa.querySelector("[jsname=yxspve]"));a.Ia||(a.Ia=a.Aa.document.body.querySelector("[jsname=yxspve]"));return a.Ia};_.L7.prototype.vr=function(){return this.Fa.matches&&!_.wFm()};
 * var CFm=function(a){var b=_.uFm(a);b&&(!(b=b.getBoundingClientRect())||0>=b.width||(b=b.top,a.vr()&&52>b&&(b=52),a.oa.style.top=b+"px",a.vr()||_.wFm()||(a.oa.style.clipPath="inset("+(52-b)+"px 0 0 0)")))};_.L7.prototype.Ic=function(a){var b=this;this.Xg=a;this.oa&&a.Aa(this).listen(function(){CFm(b)})};_.L7.prototype.scrollTo=function(a){this.Xg&&this.Xg.scrollTo(a)};_.L7.prototype.mb=function(a){this.Na=a};_.L7.prototype.rb=function(a){this.Qa=a};_.DFm=function(){};
 * _.L7.prototype.isInitialized=function(){return!!this.oa&&!!this.oa.firstChild&&(!!this.Na||!!this.Qa||!!this.tb)};_.uFm=function(a){return a.Na?a.Na.querySelector("[jsname=Ehk02]")||null:null};_.EFm=function(){};FFm=function(a,b){var c;a=(null==a?void 0:null==(c=a.xe())?void 0:_.Wg(c))||[];c=_.Ub(a);for(a=c.next();!a.done;a=c.next()){a=a.value;var d=void 0;if(null==(d=a.Db())?0:d.hasExtension(b))return a}};
 * _.vFm=function(a){return a.Qa?(a=FFm(a.Qa.HJ(),_.ju),a?(a=FFm(a,_.jF))?_.w(a.Db().getExtension(_.jF),_.iF,4)||null:null:null):null};_.L7.prototype.broadcast=function(a,b){this.isInitialized()&&_.zh.broadcast(this.oa,a,b)};_.L7.prototype.wb=function(){if(this.isInitialized()){var a;null!=(a=_.vFm(this))&&_.F(a,2)?(_.GFm(this),this.j0()):_.HFm(this)}};
 * _.GFm=function(a){if(a.isInitialized()){var b=_.uFm(a);if(b){var c,d=null==(c=_.vFm(a))?void 0:_.F(c,2);if(d){document.addEventListener("visibilitychange",a.Qb);a.Fa.addEventListener?a.Fa.addEventListener("change",a.Ya):a.Fa.addListener&&a.Fa.addListener(a.Ya);_.wFm()&&a.Aa.addEventListener("resize",a.j0);c=_.xFm(a);var e=b.getElementsByTagName("img")[0];1>=c&&e&&(e.style.display="none");e=_.Hq(b);var f;e=(null==e?void 0:null==(f=e.getData("ved"))?void 0:_.No(f))||null;a.broadcast(_.iFm,_.bFm({id:d||
 * void 0,aspectRatio:c},e||""));var g;f=a.broadcast;d={id:d||void 0,aspectRatio:c};c=(null==(g=_.vFm(a))?void 0:_.Kk(g,3))||0;f.call(a,_.jFm,{XR:d,KK:void 0===c?0:c});a.oa.style.display="block";a.oa.style.position="fixed";a.oa.style.top=b.getBoundingClientRect().top+"px";a.oa.style.left=b.getBoundingClientRect().left+"px";a.oa.style.width=b.getBoundingClientRect().width+"px";a.oa.style.height=b.getBoundingClientRect().height+"px";a.oa.style.zIndex="1030"}}}};_.L7.prototype.Lb=_.aa(364);
 * _.HFm=function(a){if(a.isInitialized()){var b=_.uFm(a);b&&(b.style.height="220px");document.removeEventListener("visibilitychange",a.Qb);a.Fa.removeEventListener?a.Fa.removeEventListener("change",a.Ya):a.Fa.removeListener&&a.Fa.removeListener(a.Ya);_.wFm()&&a.Aa.removeEventListener("resize",a.j0);_.Ogd(a.OV.oa,a.Za);a.Za=0;a.broadcast(_.mFm);a.broadcast(_.pFm);a.Ua&&(_.zh.broadcast(a.Ua,_.mFm),a.Ua=null);a.oa.style.display="none";a.oa.style.removeProperty("clip-path")}};
 * _.xFm=function(a){var b;return(a=null==(b=_.vFm(a))?void 0:_.Ok(b,1))?a:1.778};AFm=function(a){(a=_.H6g(a,{navigationUI:"hide"}))&&a.catch(function(){})};_.mq(_.zt,_.L7);
 * _.zFm=function(){return!0};
 * _.wFm=function(){return!0};
 * _.p();
 * _.m("v1daM");
 * 
 * _.p();
 * _.Lh(_.gq);
 * _.m("kHVSUb");
 * var P8c=function(a){_.kq.call(this,a.Oa)};_.D(P8c,_.kq);P8c.Va=_.kq.Va;P8c.Ka=_.kq.Ka;P8c.prototype.Tb=function(){return!1};P8c.prototype.lj=function(){return _.bi("uim","ebm")};P8c.prototype.Gk=function(){return _.bi("uim","xbm")};P8c.prototype.ZG=function(){return!1};_.mq(_.vJa,P8c);
 * _.p();
 * _.m("sTsDMc");
 * _.S8c=new _.yh(_.gq);
 * _.p();
 * _.m("LK4Pye");
 * /**var T8c;T8c=[3];_.U8c=function(){return!1};_.V8c=function(){return!1};_.OG=function(a){_.kq.call(this,a.Oa);this.Tf=a.service.Tf;this.stack=new W8c};_.D(_.OG,_.kq);_.OG.Va=_.kq.Va;_.OG.Ka=function(){return{service:{Tf:_.S8c}}};_.OG.prototype.Tb=function(){return this.Tf.Tb()};_.OG.prototype.ZG=function(){return this.Tf.ZG()};_.OG.prototype.lj=function(a){return _.U8c()?X8c(this,a,0,"enterBasicMode"):this.Tf.lj()};_.OG.prototype.Gk=function(a){return _.U8c()?X8c(this,a,1,"exitBasicMode"):this.Tf.Gk()};
 * var X8c=function(a,b,c,d){var e=Y8c(a.stack);e&&e.oa===b?e.state!==c&&(T8c.includes(b)?e.state=c:(_.coa({zc:"UIModesArbiter",methodName:d},new _.we(14,"Silk consumer is overwriting state "+b+","+e.state+","+c)),a.stack.pop())):a.stack.push(new Z8c(b,c));return $8c(a,c)},$8c=function(a,b){switch(b){case 0:return a.Tf.lj();case 1:return a.Tf.Gk();default:_.Cb(b,"state had an unknown type")}};
 * _.OG.prototype.xK=function(a){if(!_.U8c())return this.Gk(a);var b=Y8c(this.stack);if(void 0===b)return a=new _.we(13,a+" cannot restore state as there is no state to restore to."),_.ai({zc:"UIModesArbiter",methodName:"restoreToPreviousState"},a),Promise.reject(a);if(b.oa===a)return this.stack.pop(),a=this.stack.getCurrentState(),$8c(this,a);a=new _.we(13,a+" cannot restore state as "+b.oa+" has control.");_.ai({zc:"UIModesArbiter",methodName:"restoreToPreviousState"},a);return Promise.reject(a)};
 * var Z8c=function(a,b){this.oa=a;this.state=b},W8c=function(){this.items=[];this.oa=_.V8c()?0:1};W8c.prototype.getCurrentState=function(){var a=Y8c(this);return void 0!==a?a.state:this.oa};W8c.prototype.isEmpty=function(){return 0===this.items.length};var Y8c=function(a){return a.isEmpty()?void 0:a.items[a.items.length-1]};W8c.prototype.push=function(a){this.items.push(a)};W8c.prototype.pop=function(){return this.items.pop()};_.mq(_.hq,_.OG);
 * _.U8c=function(){return!0};
 * _.p();
 * _.m("Ymry6");
 * var D0e=function(a){_.kq.call(this,a.Oa);this.Lt=a.service.Lt};_.D(D0e,_.kq);D0e.Va=_.kq.Va;D0e.Ka=function(){return{service:{Lt:_.OG}}};_.h=D0e.prototype;_.h.Tb=function(){return this.Lt.Tb()};_.h.ZG=function(){return this.Lt.ZG()};_.h.lj=function(a){var b=this;return _.Ch(function(c){return c.yield(b.Lt.lj(a),0)})};_.h.Gk=function(a){var b=this;return _.Ch(function(c){return c.yield(b.Lt.Gk(a),0)})};_.h.xK=function(a){var b=this;return _.Ch(function(c){return c.yield(b.Lt.xK(a),0)})};
 * _.mq(_.xYa,D0e);
 * _.p();
 * _.m("tH4IIe");
 * _.F0e=new _.yh(_.yYa);
 * _.p();
 * _.m("MnVV2d");
 * var Pol=function(a){(new _.rf).listen(window,"pageshow",function(b){var c;!(c=b instanceof PageTransitionEvent&&b.persisted)&&(c=b instanceof _.tp)&&(b=b.Ue,c=b instanceof PageTransitionEvent&&b.persisted);(c||window.performance&&window.performance.navigation&&window.performance.navigation.type===window.performance.navigation.TYPE_RELOAD)&&a()})};_.Qol=function(){};_.Qol.prototype.oa=function(){};_.Rol=function(a){_.kq.call(this,a.Oa);var b=this;this.oa=null;this.Tf=a.service.Tf;this.Tf.Tb()&&Pol(function(){null!=b.oa&&(b.oa?b.lj():b.Gk())})};_.D(_.Rol,_.kq);_.Rol.Va=_.kq.Va;_.Rol.Ka=function(){return{service:{Tf:_.F0e}}};_.Rol.prototype.lj=function(){this.Tf.Tb()&&(this.Tf.lj(19),(new _.Qol).oa(),this.oa=!0)};_.Rol.prototype.Gk=function(){this.Tf.Tb()&&(this.Tf.Gk(19),(new _.Qol).oa(),this.oa=!1)};_.mq(_.Kdb,_.Rol);
 * _.p();
 * _.m("qMBFFe");
 * _.K7=function(a){_.kq.call(this,a.Oa);this.oa=0;this.Nm=a.service.viewport;this.ll=a.service.window;this.Ma=a.service.uuc;this.Ym=a.service.config;this.Xg=_.Zic(this.ll.get());this.document=this.ll.get().document;this.Fa=_.uj("SDsPCf")||this.document.querySelector("#gsr")};_.D(_.K7,_.kq);_.K7.Va=_.kq.Va;_.K7.Ka=function(){return{service:{viewport:_.Gv,window:_.kv,uuc:_.Rol,config:_.pB}}};
 * _.K7.prototype.Aa=function(a){a=void 0===a?null:a;if(!_.hu(this.Ym.oa()))if(a){var b=this.Fa&&this.Fa.querySelector('[data-tbnid="'+a+'"] img.rg_i');!b&&a.startsWith("sv-")&&(b=this.Fa&&this.Fa.querySelector('[data-tbnid="'+a+'"] img'));b&&(a=_.mp(b),b=this.Nm.Aa().size.height,a.top&&(a.top+a.height>this.oa+b||a.top<this.oa)&&(this.oa=a.top-b/2+a.height/2),this.Xg.oa.scrollTop=this.oa+_.HB())}else this.Xg.oa.scrollTop=this.oa+_.HB()};_.K7.prototype.Ia=function(){return!1};
 * _.K7.prototype.lj=function(){_.hu(this.Ym.oa())||this.Ma.lj()};_.K7.prototype.Gk=function(){_.hu(this.Ym.oa())||this.Ma.Gk()};_.mq(_.Ldb,_.K7);
 * _.K7.prototype.Aa=function(){};
 * _.p();
 * _.Wxm=function(a){this.Ja=_.r(a)};_.D(_.Wxm,_.u);_.Xxm=_.yd(477803390,_.Wxm);_.An[477803390]=[0];_.Yxm=function(a){this.Ja=_.r(a)};_.D(_.Yxm,_.u);_.Zxm=_.yd(479598163,_.Yxm);_.An[479598163]=[0];
 * _.m("Gi5Toe");
 * var ZGm,aHm,kHm,gHm,jHm,eHm,nHm,oHm,pHm,qHm,bHm,cHm,dHm,fHm,sHm,iHm,hHm,tHm,uHm;_.R7=function(a,b,c,d){a.xe()||a.oa(new _.Bn);a=a.xe();b=_.Vg(new _.Cn,_.Pg(new _.zn,b,c));_.Dn(a,b,d)};_.YGm=function(a){var b;return 1===(null==a?void 0:a.getType())&&9===(null==(b=a.Gc())?void 0:b.qk())};ZGm=function(a,b,c){return _.Ch(function(d){return 1==d.oa?d.yield(c.oa(_.VGm,null).oa({Xa:a,zo:b}).fetch(),2):d.return(d.Aa)})};aHm=function(a){var b;return null!=(b=_.$Gm.get(a))?b:0};
 * kHm=function(a,b,c,d,e,f,g){var k,l,n,q,t,v,x,A,E,H,L,S,W,Z,ma;return _.Ch(function(pa){if(1==pa.oa){k=Promise.resolve(f.oa(_.flc,new _.$kc).oa(c).fetch());l=a.Xk();n=_.Ws(l);_.HVc?(_.UVc(e,n),_.RVc(e,_.JVc,n)):_.WVc(e,n);q=bHm(l);t=cHm(l);dHm(l);v=_.vg(l,_.Ts,2)||_.vg(l,_.Ts,3)||_.vg(l,_.Rs,4);x=new _.pu;H=(E=A=(q||t)&&v)?x.promise.then(function(){return e.oa(l,b,a.Vk()).then(function(wa){return _.hh(wa)})}):Promise.resolve(void 0);if(A)if(g)x.resolve(),E=!1;else switch(L=aHm(n),L){case 2:setTimeout(function(){return void x.resolve()},
 * 250);break;case 1:setTimeout(function(){return void x.resolve()},25);E=!1;break;case 0:break;default:_.Cb(L,"Unsupported FetchMode")}S=eHm(c.Xa,_.ju);return pa.yield(k,2)}if(3!=pa.oa)return W=pa.Aa,Z=q&&S?fHm(e,l,S,d):null,_.HVc&&setTimeout(function(){_.VVc(e,n);_.RVc(e,_.KVc,n)},0),pa.yield(Z,3);ma=pa.Aa;return pa.return(function(){var wa=W.render(),Ca=wa.getElementsByTagName("div")[0],Ia=gHm(Ca,n);Ia&&ma&&hHm(e,n,Ia,ma);E&&_.zh.jg(Ca,_.qic,function(Da){Da.data.active&&x.resolve()});q&&Ia&&iHm(e,
 * Ia,l,a.Vk(),d,H.then(function(Da){return eHm(Da,_.ju)}),!0,!!ma);t&&(Ia=jHm(c.Xa),(Ca=_.Rh(Ca,Ca,"XiESnf")[0])&&Ia?iHm(e,Ca,l,a.Vk(),d,H.then(function(Da){var Ma;return(null==Da?0:null==(Ma=Da.Db())?0:Ma.hasExtension(_.YDb))?eHm(Da,_.ih):Da}),!1):Ca&&!Ia?_.mb(Error("hm`"+n)):!Ca&&Ia&&_.mb(Error("im`"+n)));return wa})})};gHm=function(a,b){(a=_.Rh(a,a,"bJr0R")[0])||_.mb(Error("jm`"+b));return a};
 * jHm=function(a){var b;if(null==a?0:null==(b=a.Db())?0:b.hasExtension(_.YDb)){var c;a=(null==a?void 0:null==(c=a.xe())?void 0:_.Wg(c))||[];c=_.Ub(a);for(a=c.next();!a.done;a=c.next())if(b=void 0,null==(b=a.value.Db())?0:b.hasExtension(_.ih))return!0}return!1};
 * eHm=function(a,b){var c;if(null==a?0:null==(c=a.Db())?0:c.hasExtension(_.YDb)){var d;a=(null==a?void 0:null==(d=a.xe())?void 0:_.Wg(d))||[];d=_.Ub(a);for(a=d.next();!a.done;a=d.next()){a=a.value;var e=c=void 0,f=void 0;if((null==(c=a.Db())?0:c.hasExtension(b))&&1===(null==(e=a.xe())?void 0:null==(f=_.Wg(e))?void 0:f.length))return b=void 0,null==(b=a.xe())?void 0:_.iKc(b,0)}}};
 * nHm=function(a){var b;if(null==(b=a.xe())||!_.Wg(b).length){b=_.Ub(lHm.new({Xa:a}));for(var c=b.next();!c.done;c=b.next())c=c.value,c.eba()&&c.mba()}var d;if(null==(d=a.xe())?0:_.Wg(d).length)for(a=_.Ub(_.mHm.new({Xa:a})),d=a.next();!d.done;d=a.next())d=d.value,d.eba()&&d.mba()};
 * oHm=function(a,b){var c;if(b=null==b?void 0:null==(c=b.Gc())?void 0:c.getUniqueId())c=(c=document.querySelector('.ViTmJb[data-tbnid="'+b+'"] img.rg_i[src^="data:"],.ViTmJb[data-tbnid="'+(b+'"] img.rg_i[src$="&reload=on"]')))&&c.src&&0<c.naturalWidth&&0<c.naturalHeight?c.src:void 0,c&&a.S8b(c)};pHm=function(a,b){var c=_.so(_.Gt);b=(0,_.Yp.HBa)(b);c=c.oa;b=(null==b?void 0:_.Mg(b,1,-1))||-1;if(c.oa.length)a();else if(0>b||b>=c.Aa.length)a();else{c.oa.push(new _.Gfb(b,!1,!1));try{a()}finally{c.oa.pop()}}};
 * qHm=function(){var a='<div class="'+_.C("Ickom")+'">';return(0,_.K)(a+"Failed to load, please try again.</div>")};bHm=function(a){a=_.Ws(a);return _.FVc.has(a)};cHm=function(a){a=_.Ws(a);return!_.IVc.has(a)&&_.EVc.has(a)};dHm=function(a){a=_.Ws(a);_.IVc.has(a)};
 * fHm=function(a,b,c,d){var e,f,g,k,l,n;return _.Ch(function(q){if(1==q.oa){e=_.Ws(b);f=_.FVc.get(e);g=f.Dp;k=f.c5a;if(!g)return q.return(Promise.resolve(null));_.HVc?(_.RVc(a,_.JVc,e),_.RVc(a,_.KVc,e)):_.RVc(a,_.sF,e);l=a.Nf;n=l.oa;return q.yield(k(b),2)}return q.return(n.call(l,g,q.Aa).oa({Xa:c,zo:d}).fetch())})};_.rHm=function(a,b){_.zh.trigger(b||a.fl.get().document.body,_.Vjc);a=a.Rb.Kc(qHm);b&&_.Hq(b).empty().append(a);return a};
 * sHm=function(a,b,c,d,e,f){f=void 0===f?!1:f;try{var g=d.render(),k=_.Hq(c),l=k.children();if(l.el()){var n;null==(n=l.first())||n.replaceWith(g);l.remove()}else k.append(g);_.Bb([_.TVc],c,"decode-data-ved","1");_.tB();e||_.zh.trigger(c,_.Wjc);return g}catch(t){var q;_.mb(Error("Ne`"+(f?"update":"render")+"`"+(e?"hero":"dynamic")+"`"+b+"`"+(null==(q=t)?void 0:q.message),{cause:t}));f?(_.zh.trigger(c,_.Vjc),a=c):a=_.rHm(a,c);return a}};
 * iHm=function(a,b,c,d,e,f,g,k){k=void 0===k?!1:k;var l,n,q,t,v,x,A,E,H,L;_.Ch(function(S){switch(S.oa){case 1:return l=_.Ws(c),n=g?_.FVc.get(l):_.EVc.get(l),q=n.Dp,t=n.c5a,_.Dh(S,2),S.yield(f,4);case 4:v=S.Aa;_.ji(S,3);break;case 2:return x=_.Eh(S),_.mb(Error("Me`"+l+"`"+(null==(A=x)?void 0:A.message),{cause:x})),k||_.rHm(a,b),S.return();case 3:if(!v)return S.return();E=a.Nf;H=E.oa;return S.yield(t(c),6);case 6:return S.yield(H.call(E,q,S.Aa).oa({Xa:v,zo:e}).fetch(),5);case 5:L=S.Aa,a.Hd.Md(function(){return sHm(a,
 * l,b,L,g,k)},{wd:_.th(b,1),yd:_.vh(b,3,k)},!0),g||_.Dgc(a.wk,d),_.hi(S)}})};hHm=function(a,b,c,d){var e=_.de(c,"ved");e?pHm(function(){return sHm(a,b,c,d,!0)},e):sHm(a,b,c,d,!0)};tHm=function(a){var b=new _.hll;return _.Hg(b,1,a)};uHm=function(){this.oa=[]};uHm.prototype.register=function(a){this.oa.push(a)};uHm.prototype.new=function(a){return this.oa.map(function(b){return b(a)})};var vHm=[0,_.EE,_.GE,_.Bm,_.GE,_.xEc,_.et,_.EE,_.GE,1,_.GE,-2,_.EE];var wHm=[0,_.EE,_.yEc,_.zEc];var xHm=[0,_.EE,_.BEc,_.CEc,1,_.et];var yHm=[0,1,_.Bm,[0,_.I,_.et]];var zHm=function(a){this.Ja=_.r(a)};_.D(zHm,_.u);zHm.prototype.getImageUrl=function(){return _.w(this,_.Yg,1)};zHm.ob=[8];var AHm=[0,_.et,_.gm,vHm,wHm,yHm,xHm,_.J,_.Bm,[0,_.J,_.I,function(){return AHm}],_.I,_.J];_.Rn[7E3]=AHm;var BHm=_.yd(521763365,zHm);_.An[521763365]=AHm;var lHm;lHm=new uHm;_.mHm=new uHm;_.CHm=function(){return!1};_.DHm=function(a){this.Xa=a};_.DHm.prototype.eba=function(){var a,b=null==(a=this.Xa.Db())?void 0:a.getExtension(_.tg),c,d,e;return _.YGm(b)&&_.CHm()||1===(null==b?void 0:b.getType())&&!_.YGm(b)&&!0!==(null==b?void 0:null==(c=b.Gc())?void 0:null==(d=c.getExtension(_.Tx))?void 0:null==(e=_.Sx(d))?void 0:e.rG())};
 * _.DHm.prototype.mba=function(){var a,b=null==(a=this.Xa.Db())?void 0:a.getExtension(_.tg);_.R7(this.Xa,_.yxm,new _.xxm);_.R7(this.Xa,_.uxm,new _.txm);var c;if(16===(null==b?void 0:null==(c=b.Gc())?void 0:_.Hk(c,1))){var d,e,f;a=this.Xa;c=new _.hxm;b=null!=(f=null==b?void 0:null==(d=b.Gc())?void 0:null==(e=d.getExtension(_.Qg))?void 0:e.Rr())?f:"";d=_.Hg(c,1,b);_.R7(a,_.ixm,d)}else{_.R7(this.Xa,_.Axm,new _.zxm);var g;9!==(null==b?void 0:null==(g=b.Gc())?void 0:_.Hk(g,1))&&_.R7(this.Xa,_.Rxm,(new _.Qxm).setComponent(1));
 * this.oa(this.Xa);_.R7(this.Xa,_.Txm,new _.Sxm);_.R7(this.Xa,_.wxm,new _.vxm)}};_.DHm.prototype.oa=function(){};lHm.register(function(a){return new _.DHm(a.Xa)});_.$Gm=new Map;var EHm,HHm,IHm;EHm=new Set([100003,31,7]);_.FHm=function(a){_.kq.call(this,a.Oa);this.Nf=a.service.component;this.gJ=a.service.Fla;this.oe=null};_.D(_.FHm,_.kq);_.FHm.Va=_.kq.Va;_.FHm.Ka=function(){return{service:{component:_.Bu,Fla:_.tF}}};
 * _.FHm.prototype.xG=function(a){var b=this,c,d,e,f,g,k,l,n,q,t,v,x,A;return _.Ch(function(E){switch(E.oa){case 1:c=a.Ah;e=(null==(d=c)?void 0:d.HJ())||a.Xa;g=null==(f=e.Db())?void 0:f.getExtension(_.tg);nHm(e);if(null==(k=e.xe())||!_.Wg(k).length)return E.return();oHm(a.ambientParams,g);return E.yield(_.GHm(b,e,g),2);case 2:if(l=E.Aa||HHm(c)||IHm(e,c,g))c=l,e=l.HJ();n={Xa:e,zo:a.ambientParams,Ah:c,Xd:g};if((v=null==(q=c)?void 0:null==(t=q.Xk())?void 0:_.Ws(t))&&(!g||EHm.has(v))&&c&&_.FVc.has(v))return E.return(kHm(c,
 * a.A3,n,a.ambientParams,b.gJ,b.Nf,!!a.isActive));if(1!==(null==(x=g)?void 0:x.getType())){E.Hb(3);break}return E.yield(ZGm(e,a.ambientParams,b.Nf),4);case 4:return A=E.Aa,E.return(function(){return A.render()});case 3:return E.return(Promise.reject(Error("km`"+v)))}})};HHm=function(a){if(a&&!_.ek(a,_.Vs,1,_.Fdb)){var b=a.HJ(),c;if(null==b?0:null==(c=b.Db())?0:c.hasExtension(BHm))return _.wt(_.ut(a.clone(),_.Xs(31)),_.Ru(b,!1,null))}return null};
 * IHm=function(a,b,c){var d,e;return _.YGm(c)&&!_.CHm()&&(null==b||!_.ek(b,_.Vs,1,_.Fdb)||(null==b?0:null==(d=b.HJ())?0:null==(e=d.Db())?0:e.hasExtension(_.tg)))?_.wt(_.vt(_.ut(new _.tt,_.Xs(100003)),null==c?void 0:c.getId()),_.Ru(a,!1,null)):null};_.GHm=function(){return _.Ch(function(a){return a.return(null)})};_.mq(_.Eib,_.FHm);var JHm=function(a){this.Xa=a};JHm.prototype.eba=function(){var a,b=null==(a=this.Xa.Db())?void 0:a.getExtension(_.tg);return _.YGm(b)&&!_.CHm()};
 * JHm.prototype.mba=function(){var a,b=null==(a=this.Xa.Db())?void 0:a.getExtension(_.tg),c,d,e;a=0<(null==b?void 0:null==(c=b.Gc())?void 0:null==(d=c.getExtension(_.Tx))?void 0:null==(e=_.Rx(d))?void 0:_.Mg(e,25));var f,g,k;b=1<(null==b?void 0:null==(f=b.Gc())?void 0:null==(g=f.getExtension(_.Tx))?void 0:null==(k=_.Rx(g))?void 0:_.Mg(k,2));_.R7(this.Xa,_.yxm,new _.xxm);a?_.R7(this.Xa,_.Zxm,new _.Yxm):_.R7(this.Xa,_.uxm,new _.txm);_.R7(this.Xa,_.Axm,new _.zxm);b&&_.R7(this.Xa,_.Xxm,new _.Wxm);_.R7(this.Xa,
 * _.Rxm,(new _.Qxm).setComponent(1));_.R7(this.Xa,_.Txm,new _.Sxm);_.R7(this.Xa,_.wxm,new _.vxm)};lHm.register(function(a){return new JHm(a.Xa)});var KHm=function(a){this.Xa=a};KHm.prototype.eba=function(){var a,b=null==(a=this.Xa.Db())?void 0:a.getExtension(_.tg),c,d,e;return 1===(null==b?void 0:b.getType())&&!0===(null==b?void 0:null==(c=b.Gc())?void 0:null==(d=c.getExtension(_.Tx))?void 0:null==(e=_.Sx(d))?void 0:e.rG())};
 * KHm.prototype.mba=function(){var a,b=null==(a=this.Xa.Db())?void 0:a.getExtension(_.tg),c;a=null==b?void 0:null==(c=b.Gc())?void 0:c.getExtension(_.bhl);var d,e;if((null==b?0:null==(d=b.Gc())?0:null==(e=d.getUniqueId())?0:e.endsWith("regis-generate-more-viewer"))&&1!==a.Me()){_.R7(this.Xa,_.yxm,new _.xxm);_.R7(this.Xa,_.jll,_.ill(tHm(""),_.Fk(a,3,_.mk())));_.R7(this.Xa,_.kxm,new _.jxm);b=this.Xa;var f=new _.MKc;a=a.Me();a=_.sl(f,6,a);_.R7(b,_.NKc,a)}else{var g;c=null==b?void 0:null==(g=b.Gc())?void 0:
 * g.Ie();b=null==b?void 0:null==(f=b.Gc())?void 0:f.getExtension(_.Qg);_.R7(this.Xa,_.yxm,new _.xxm);1!==a.Me()&&_.R7(this.Xa,_.jll,_.ill(tHm(c.getUrl()),_.Fk(a,3,_.mk())));_.R7(this.Xa,_.uxm,new _.txm);f=this.Xa;g=new _.Khl;g=_.Hg(g,1,_.Xg(a,1));g=_.Hg(g,2,_.Xg(a,2));d=_.Fk(a,3,_.mk());g=_.ok(g,8,d);d=c.getUrl();g=_.Hg(g,3,d);d=b.Fo();g=_.Hg(g,4,d);d=b.Rr();g=_.Hg(g,5,d);d=c.Rc();g=_.fl(g,6,d);c=c.Jc();c=_.fl(g,7,c);g=a.Me();c=_.sl(c,9,g);_.R7(f,_.Lhl,c);_.jk(a,6)&&_.R7(this.Xa,_.Rxm,(new _.Qxm).setComponent(1));
 * f=this.Xa;c=new _.MKc;c=_.Hg(c,2,_.Xg(a,1));g=b.Fo();c=_.Hg(c,4,g);c=_.Hg(c,3,_.Xg(a,2));b=b.Rr();b=_.Hg(c,5,b);a=a.Me();a=_.sl(b,6,a);_.R7(f,_.NKc,a);_.R7(this.Xa,_.wxm,new _.vxm)}};lHm.register(function(a){return new KHm(a.Xa)});
 * 
 * var LHm=function(a){this.Xa=a};LHm.prototype.eba=function(){var a;if(null==(a=this.Xa.xe())?0:_.Wg(a).some(function(d){var e;return null==(e=d.Db())?void 0:e.hasExtension(_.gym)}))return!1;var b;a=null==(b=this.Xa.Db())?void 0:b.getExtension(_.tg);var c;b=(null==a?void 0:null==(c=_.Pn(a))?void 0:_.Pk(c,3,0))||0;return 1===(null==a?void 0:a.getType())&&0===b};
 * LHm.prototype.mba=function(){var a,b,c=null!=(b=null==(a=this.Xa.xe())?void 0:_.Wg(a).findIndex(function(f){var g;return null==(g=f.Db())?void 0:g.hasExtension(_.yxm)}))?b:-1;_.R7(this.Xa,_.gym,new _.fym,0<=c?c+1:void 0);var d,e;a=null!=(e=null==(d=this.Xa.xe())?void 0:_.Wg(d).findIndex(function(f){var g;return null==(g=f.Db())?void 0:g.hasExtension(_.uxm)}))?e:-1;_.R7(this.Xa,_.eym,new _.dym,0<=a?a+1:void 0)};_.mHm.register(function(a){return new LHm(a.Xa)});
 * 
 * 
 * _.p();
 * _.m("gpa7Te");
 * _.QHm=new Map;var RHm={};var SHm;SHm=_.si(function(){for(var a=_.Ub(_.QHm.entries()),b=a.next();!b.done;b=a.next()){var c=_.Ub(b.value);b=c.next().value;c=c.next().value;RHm[b]=c}});_.THm=function(a){_.kq.call(this,a.Oa);this.oe=null;SHm();this.Hd=a.service.Bd;this.gJ=a.service.Fla;this.oa=a.service.YZc};_.D(_.THm,_.kq);_.THm.Va=_.kq.Va;_.THm.Ka=function(){return{service:{Bd:_.Zv,Fla:_.tF,YZc:_.FHm}}};
 * _.THm.prototype.LJa=function(a){var b=this,c,d,e,f,g,k;return _.Ch(function(l){if(1==l.oa)return l.yield(b.oa.xG(a),2);if(3!=l.oa){if(c=l.Aa)return l.return(c);e=null==(d=a.Xa.Db())?void 0:_.ug(d,_.tg);if(!e)return l.return(function(){return _.rHm(b.gJ,null)});f=e.getType();return(g=RHm[f])?l.yield(_.Jna(g,b,b.Ci()),3):l.return(function(){return _.rHm(b.gJ,null)})}k=l.Aa;return l.return(function(){return k.render(Object.assign({},a,{Xd:e}))})})};_.mq(_.Fib,_.THm);
 * 
 * 
 * _.p();
 * var iXi=function(a){var b=[];a=hXi(a,0,b);if(1<b.length)for(var c=_.Ub(b),d=c.next();!d.done;d=c.next()){d=d.value;var e=void 0,f=a-d.options.duration-(null!=(e=d.options.delay)?e:0);0!==f&&(d.options.endDelay=f)}return{hmc:b,duration:a}},hXi=function(a,b,c){if(Array.isArray(a)){var d=0;a=_.Ub(a);for(var e=a.next();!e.done;e=a.next())e=hXi(e.value,b,c),e>d&&(d=e);return d}d={};e=Object.assign({},a,{Jsb:d});e.options=Object.assign({},a.options);var f=a.options.duration,g,k=null==(g=a.options.token)?
 * void 0:g.duration;e.options.duration=null!=f?f:k;var l;f=a.options.easing;g=null==(l=a.options.token)?void 0:l.easing;if(l=null!=f?f:g)e.options.easing=l;l=_.Ub(jXi);for(f=l.next();!f.done;f=l.next())for(f=f.value,g=_.Ub(a.keyframes),k=g.next();!k.done;k=g.next())if(null!=k.value[f]){d[f]=!0;break}b&&(e.options.delay=(e.options.delay||0)+b);c.push(e);b=e.options;return b.duration+(b.delay||0)},kXi=document.createDocumentFragment?function(){return document.createDocumentFragment()}:function(){return document.createElement("div")},
 * lXi=function(){a:{var a;if("function"===typeof(null==(a=EventTarget)?void 0:a.constructor))try{var b=new EventTarget;break a}catch(c){}b=kXi()}this.Qy=b;this.oa=this.UCa=new _.pu};lXi.prototype.addEventListener=function(a,b,c){this.Qy.addEventListener(a,b,c)};lXi.prototype.removeEventListener=function(a,b,c){this.Qy.removeEventListener(a,b,c)};lXi.prototype.dispatchEvent=function(a){return this.Qy.dispatchEvent(a)};var jXi=["transform","opacity"];var mXi=function(a,b){lXi.call(this);var c=this;this.XS=[];a=iXi(a);var d=a.hmc;this.vR=a.duration;a=function(){a:{for(var t=_.Ub(c.XS),v=t.next();!v.done;v=t.next())if("finished"!==v.value.animation.playState)break a;c.oa&&(c.oa.resolve(),c.oa=void 0);c.dispatchEvent(new Event("finish"))}};for(var e=_.Ub(d),f=e.next();!f.done;f=e.next()){var g=f=f.value,k=g.target,l=g.keyframes,n=g.Jsb;if(1===l.length){g={};n=_.Ub(Object.keys(n));for(var q=n.next();!q.done;q=n.next())q=q.value,g[q]=_.ep(k,q);f.keyframes=
 * [g].concat(_.Qh(l))}}d=_.Ub(d);for(e=d.next();!e.done;e=d.next())l=e=e.value,f=l.target,k=l.keyframes,l=l.options,l.fill="both",l.composite="replace",f=f.animate(k,l),k=void 0,(null==(k=b)?0:k.SMc)||f.pause(),f.onfinish=a,this.XS.push({effect:e,animation:f})};_.D(mXi,lXi);mXi.prototype.play=function(){for(var a=_.Ub(this.XS),b=a.next();!b.done;b=a.next())b.value.animation.play()};mXi.prototype.finish=function(){for(var a=_.Ub(this.XS),b=a.next();!b.done;b=a.next())b.value.animation.finish()};
 * mXi.prototype.pause=function(){for(var a=_.Ub(this.XS),b=a.next();!b.done;b=a.next())b.value.animation.pause()};mXi.prototype.reverse=function(){for(var a=_.Ub(this.XS),b=a.next();!b.done;b=a.next())b.value.animation.reverse()};_.nXi=function(){var a=_.bb.apply(0,arguments);this.oa=!1;this.specs=Array.from(a)};_.nXi.prototype.attach=function(a){this.specs.push(a);return this};_.nXi.prototype.initialize=function(){var a=this;return _.Ch(function(b){return b.return(oXi(a))})};var oXi=function(a){var b={SMc:!1},c;return _.Ch(function(d){a.oa=!0;c=new mXi(a.specs,b);return d.return(Promise.resolve(c))})};
 * 
 * _.Fbl={};
 * _.m("yx4a8e");
 * _.Hbl=function(a,b){b=void 0===b?{}:b;_.Gbl.set(a,b)};_.Gbl=new Map;_.Ibl=null;_.Jbl=new _.cjc;
 * _.Hbl(16,_.Fbl);
 * _.Fbl.W0c=!0;
 * _.p();
 * _.m("GhG1be");
 * var Qtm;_.r7=function(a){_.kq.call(this,a.Oa);this.callbacks=new Map;this.oa={};this.Fa=new Map;this.Ed=new _.rf;this.Dh=a.service.Se;this.Ia=a.service.ypa;this.window=a.service.window.get();this.Aa=new _.Xe("s","vhs");_.Kh(this,this.Ed);this.init()};_.D(_.r7,_.kq);_.r7.Va=_.kq.Va;_.r7.Ka=function(){return{service:{Se:_.Hv,window:_.kv,ypa:_.hic}}};_.r7.prototype.init=function(){this.oa=this.Aa.get("vhk")||{};Qtm(this)};
 * _.Rtm=function(a,b,c){c=void 0===c?{}:c;c.preventDefault&&b.event.preventDefault&&b.event.preventDefault();var d=b.actionElement.rc("href")||b.targetElement.rc("href");_.Qe(1,d)||_.Gqa(d)||(d="https://"+_.hgl()+d);c.n8&&a.Dh.n8();c=_.Oo(b.actionElement.getData("ictx"),"")||_.Oo(b.targetElement.getData("ictx"),"");_.iic(a.Ia,d,b.event,c?{ictx:c}:void 0)||_.Gb(a.window.location,_.ab(d))};
 * Qtm=function(a){a.Ed.listen(a.window,"pageshow",function(){a.handleEvent(1)},!1);a.Ed.listen(a.window.document,"visibilitychange",function(){"visible"===a.window.document.visibilityState&&a.handleEvent(2)},!1);var b=_.zh.listen(a.window.document.body,_.SRb,function(d){d.data.Mt&&(a.oa[d.data.Mt]=Date.now(),a.Aa.set("vhk",a.oa))}),c=_.zh.listen(a.window.document.body,_.TRb,function(){a.handleEvent(3)});a.addOnDisposeCallback(function(){_.zh.Dg(b);_.zh.Dg(c)})};
 * _.r7.prototype.clear=function(){this.oa={};this.Aa.clear()};_.r7.prototype.handleEvent=function(a){var b=this.Dh.FQ()||"";if(b){var c=this.Dh.T5()?this.Dh.DCc()?2:1:0;this.oa[b]&&this.fireEvent(c,b,a);this.Fa.has(c)&&this.oa[b]&&this.Fa.get(c)();this.clear()}};_.r7.prototype.fireEvent=function(a,b,c){this.callbacks.has(a)&&this.callbacks.get(a)(b,c)};_.mq(_.ieb,_.r7);
 * _.p();
 * _.hpg=function(a){this.Ja=_.r(a,3)};_.D(_.hpg,_.u);_.ipg=function(a,b){return _.sl(a,1,b)};var jpg=function(a){this.Ja=_.r(a)};_.D(jpg,_.u);_.kpg=new _.wf("cinoBd",jpg,_.hpg,[{key:_.Wq,value:!0},{key:_.Zq,value:"/ViewerService.WriteFootprint"}]);
 * _.OEm=new function(){this.oa=new _.Xe("s","ipCIQc")};
 * _.m("PeYuVe");
 * _.S7=function(a){_.Wh.call(this,a.Oa);this.O5=this.g_=!1;this.Ym=a.service.config;this.ah=a.service.data;this.sQa=a.service.Rna;this.wk=a.service.wk;this.Jb=a.service.qc;this.uKa=a.service.ysa;this.Hd=a.service.Bd;this.Rb=a.Kb.soy;this.Aab=a.service.yab;this.Dh=a.service.Se;this.oa=a.model.EW;this.window=a.service.window;this.oe=null;this.Wua=_.ig(function(){return _.sj("M9JG3")})};_.D(_.S7,_.Wh);
 * _.S7.Ka=function(){return{Kb:{soy:_.It},model:{EW:_.aFm},service:{config:_.pB,data:_.Ku,Rna:_.r7,wk:_.iB,qc:_.Uv,ysa:_.uol,Bd:_.Zv,yab:_.THm,Se:_.eB,window:_.kv}}};_.S7.prototype.Na=function(){return this.oa.QM()};_.S7.prototype.yna=function(a){_.Rtm(this.sQa,a,{preventDefault:!0})};_.di.Object.defineProperties(_.S7.prototype,{Ma:{configurable:!0,enumerable:!0,get:function(){return this.oa.Na}}});_.U(_.S7.prototype,"s370ud",function(){return this.yna});_.U(_.S7.prototype,"yArZRd",function(){return this.Na});
 * _.fv(_.S7);
 * 
 * 
 * _.p();
 * _.Idj=_.T("kyj0be");
 * var wbl;_.qbl=function(a){a=a.getBoundingClientRect();var b=a.top,c=a.right,d=a.left;return 0<a.bottom&&0<c&&d<(_.n1||window).innerWidth&&b<(_.n1||window).innerHeight};_.rbl=function(){var a=_.n1||window||window,b=_.Bqa("snapshot-api-element");b=_.Wf(b,"data-")?b:"data-"+b;return Array.from(a.document.querySelectorAll("["+b+"]"))};
 * _.ybl=function(a,b){b=void 0===b?{}:b;var c=_.sbl(a,b),d=a.cloneNode(!0),e=[d].concat(_.Qh(d.querySelectorAll(tbl)));e=_.Ub(e);for(var f=e.next();!f.done;f=e.next()){f=f.value;for(var g=_.Ub(ubl),k=g.next();!k.done;k=g.next())f.removeAttribute(k.value)}e="true";e=void 0===e?"":e;f=_.Bqa("snapshot-api-element");f=_.Wf(f,"data-")?f.replace("data-",""):f;f=_.Aqa(f);_.Wp(d,f,e);f=c;f=void 0===f?window.document.body:f;e=a.tagName;k=f;k=void 0===k?document.body:k;f=vbl.get(k);f||(f=new Map,vbl.set(k,f));
 * f.has(e)?e=f.get(e):(g=document.createElement(e),k.appendChild(g),k=wbl(g),g.remove(),f.set(e,k),e=k);f=wbl(a);for(var l in f)f[l]!==e[l]&&(d.style[l]=f[l]);d.style.height||(d.style.height=f.height);d.style.width||(d.style.width=f.width);d.style.position=b.fixed?"fixed":"absolute";b.xNc||c.appendChild(d);b.yNc||_.xbl(d,a,b);return d};_.sbl=function(a,b){b=void 0===b?{}:b;return b.ZEd||a.closest("body")||document.body};_.zbl=function(){var a=_.rbl();a=_.Ub(a);for(var b=a.next();!b.done;b=a.next())b.value.remove()};
 * wbl=function(a){a=window.getComputedStyle(a);for(var b={},c=_.Ub(Abl),d=c.next();!d.done;d=c.next())d=d.value,b[d]=a[d];return b};_.xbl=function(a,b,c){c=void 0===c?{}:c;var d=c.tBa||"top-left",e=c.Xec||{},f=_.n1||window,g,k=e.fYc||(null==b?void 0:null==(g=b.getBoundingClientRect)?void 0:g.call(b))||b,l;b=null!=(l=e.g1c)?l:f.scrollX;var n;e=null!=(n=e.h1c)?n:f.scrollY;d.includes("top")&&(a.style.top=k.y+(c.fixed?0:e)+"px");d.includes("left")&&(a.style.left=k.x+(c.fixed?0:b)+"px")};var ubl=[].concat(_.Qh(["jsaction","jscontroller","jsmodel","jslog","jsname"]),["id"]),tbl=ubl.map(function(a){return"["+a+"]"}).join(","),Abl="height width font border color background borderRadius zIndex".split(" "),vbl=new WeakMap;
 * _.mum=new function(){this.cache={};this.oa={}};
 * _.Bxd=new _.qIa;
 * 
 * var xyd;_.wyd=function(a,b,c){c=void 0===c?!1:c;b=b.EEa();_.ia(b)||_.cp(a,b);c&&_.bsa(a.clientTop)};_.yyd=function(){xyd||(xyd=void 0!==_.Bj("DIV").style.transform?"transform":_.eGa()+"-transform ");return xyd};xyd=null;
 * 
 * var Byd=function(){this.oa=null;this.Fa=!1;this.Aa=_.Le()};Byd.prototype.init=function(a,b,c){this.Fa||(this.Fa=!0,_.wyd(a,b,c))};Byd.prototype.play=function(a,b,c,d){this.init(a,b,!0);b=[];c.g5()&&b.push("opacity "+d.Aa());c.wNa()&&b.push(_.yyd()+" "+d.Fa());b=b.join(",");_.cp(a,{transition:b,animation:"qs-timer "+d.oa()+"ms"});d=Cyd(this,a);_.wyd(a,c);return d};Byd.prototype.finish=function(a,b){_.wyd(a,b);Dyd(this,a);this.Aa.resolve(null)};
 * var Cyd=function(a,b){_.ep(b,"display");a.oa=_.Se(b,_.PGa,function(c){c.target===b&&(c.stopPropagation(),Dyd(a,b),a.Aa.resolve(null))},!1,a);return a.Aa.promise},Dyd=function(a,b){a.oa&&(_.yp(a.oa),a.oa=null);_.cp(b,{transition:"",animation:""})};_.rIa(_.Bxd,Byd);
 * _.m("J29Kkd");
 * var eIm,jIm,lIm,mIm,nIm,oIm,pIm,rIm,sIm,uIm,vIm,wIm,xIm,AIm,BIm,CIm,gIm;eIm=function(a){var b=(0,_.Gdb)(a)?a:void 0;a=_.OB(a);!b&&a&&a.hasExtension(_.Idb)&&(b=_.w(_.ug(a,_.Idb),_.tt,1));return b};_.fIm=function(){var a=new _.fq,b=_.mJa(new _.lJa,_.jJa(new _.iJa,323));return _.ud(a,_.lJa,5,b)};_.iIm=function(a,b){var c=a=a||new _.Dt,d=new _.wF,e=new gIm;b=_.sl(e,2,b);_.oWc(c,_.Pg(d,hIm,b));return a};jIm=function(a,b){return a.map(b)};_.kIm=function(a){return _.No(a.getData("tbnid"))};
 * lIm=function(a){return _.kIm(a)?a.getData("pending").uc()?1:2:0};_.eB.prototype.Noa=_.ba(117,function(a){a=null!=a?a:this.oM();return"/imgres"===a.pathname||a.pathname.startsWith("/viewer/")});mIm=function(a){var b=new _.kSb;a.Aa=b};nIm=function(a){a.Ia=a.oa||a.Ia;if(a.Aa){var b;a.Aa===(null==(b=a.getState())?void 0:b.id)?a.Km({replace:!0}):a.history.pop(a.Aa,!0).then(function(){a.T5()?a.Km({replace:!0}):a.Fj(!0,!0)},function(){a.Aa=null;a.Km({})})}else a.Km({})};
 * oIm=function(a,b,c,d){_.ugc.has(b)&&(a=a.oa.get(c))&&a.Fa.resolve(d)};pIm=function(a,b){a=a.oa.get(b);var c;(null==a?0:null==(c=a.Vf)?0:null!=c.Aa.startTime)&&null!=a&&a.SU&&(null==a||!a.Aa)&&(a.Aa=!0,_.hB(a.Vf,"uvphcdt"),a.Na.resolve())};_.qIm=function(a,b,c){if(a=a.oa.get(b))if(c=(0,_.Yp.Rpc)(c))if(c=(0,_.Yp.Sca)(c))a.Ya=c};rIm=function(a,b,c){var d;null!=(d=a.oa.get(b))&&d.SU&&_.qIm(a,b,c)};
 * sIm=function(a,b){a=[document.body].concat(_.Qh([].concat(_.Qh(a.oa.Aa)).map(function(e){return e.content})));b='[jsname="N9Xkfe"]'+b;for(var c=0;c<a.length;c++){var d=a[c].querySelector(b);if(d)return _.Hq(d)}return null};_.tIm=function(a,b,c){return b?sIm(a,"["+(void 0===c?"data-tbnid":c)+'="'+b+'"]'):null};uIm=function(a,b){return!!a.QM().find(function(c){return c.Vk()===b})};vIm=function(a,b){return a.QM().findIndex(function(c){return c.Vk()===b})};
 * wIm=function(a){if(void 0===a.Ia){if(a.k_)var b=a.oa;else{b=a.MB.getScope(a.oa).oa;var c=_.P9a(b,_.O9a(b,a.YF));b=_.Q9a(b,c);b=b[b.length-1].id()}a.Ia=b}return a.Ia};xIm=function(a){_.hu(a.Ym.oa())||(a.oa=a.Xg.oa.scrollTop-_.HB())};
 * _.yIm=function(a,b){var c=a.document.documentElement,d=a.document.body;if(!_.hu(a.Ym.oa()))for(b?([c,d].forEach(function(e){return void _.cp(e,"overscrollBehaviorY","")}),_.cp(d,"overflow",""),a.Ia()&&(_.cp(c,"overflow",""),a.Aa(),[c,d].forEach(function(e){return void _.cp(e,"height","")}))):([c,d].forEach(function(e){return void _.cp(e,"overscrollBehaviorY","none")}),_.cp(d,"overflow","hidden"),a.Ia()&&(xIm(a),_.cp(c,"overflow","hidden"),[c,d].forEach(function(e){return void _.cp(e,"height","100%")}))),
 * a=[].concat(_.Qh(a.document.querySelectorAll("#kO001e,#gsr,header")),[_.uj("z1Vi9d"),_.uj("Lj9fsd")]),a=_.Ub(a),c=a.next();!c.done;c=a.next())(c=c.value)&&_.cp(c,{visibility:b?"":"hidden"})};_.zIm=function(a,b,c){var d;return _.Ch(function(e){if(1==e.oa)return e.yield(a.LJa(c),2);d=e.Aa;return e.return(b(function(){return d()}))})};AIm=function(a,b,c){return _.Ch(function(d){return d.return(_.zIm(a,function(e){return _.AUb(a.Hd,e,c)},b))})};
 * BIm=function(a){a=a||{};var b=a.pF;a=a.Pb;b="<div"+_.O(_.dx())+(null!=a?" ssk='"+_.C(_.Ar("uulWId")+a)+"'":"")+_.y(new _.R(_.U0b,_.qt(new _.lt,_.Pg(new _.gt,_.Skc,_.Rkc(b)))),!1)+"></div>";return(0,_.K)(b)};CIm=function(a){a=a||{};var b=a.pF;a=a.Pb;b="<div"+_.O(_.dx())+(null!=a?" ssk='"+_.C(_.Ar("pppBnc")+a)+"'":"")+_.y(new _.R(_.T0b,_.qt(new _.lt,_.Pg(new _.gt,_.Skc,_.Rkc(b)))),!1)+"></div>";return(0,_.K)(b)};gIm=function(a){this.Ja=_.r(a)};_.D(gIm,_.u);
 * var hIm=_.yd(257,gIm),DIm=function(a){this.Ja=_.r(a)};_.D(DIm,_.u);_.h=DIm.prototype;_.h.getImageUrl=function(){return _.F(this,1)};_.h.Fo=function(){return _.F(this,2)};_.h.Zq=function(){return _.Xk(this,2)};_.h.getPosition=function(){return _.Mg(this,4)};_.h.setPosition=function(a){return _.fl(this,4,a)};_.h.uda=function(){return _.w(this,_.ge,5)};
 * var EIm=_.yd(1E3,DIm),FIm=[1,6,23],GIm=function(a,b){var c,d=null==(c=_.OB(b))?void 0:c.getType();if(d&&!FIm.includes(d))return _.mb(Error("lm")),null;c=b.Vk();if(null!=a.oa.Qa&&23!==d){var e=_.OEm;a=c?(a=e.oa.get(a.oa.Qa))&&_.ya(a)?a[c]||null:null:null;return a?new _.uh(a,3):null}a:if(d=a.oa,(0,_.Gdb)(b)&&_.F(b,5))e=new _.uh(_.F(b,5),3);else{if(b=_.OB(b)){var f,g;d=d.uKa;if(b.getId()){var k="data-tbnid",l=b.getId();_.Cla(b)&&(k="data-id");var n;if(null!=(n=null==(g=b.Gc())?void 0:g.hasExtension(_.bhl))&&
 * n){g=l.split("-");if(2>g.length)throw Error("ek`"+l);l=g[0]+"-"+g[1]}g=_.tIm(d,l,k)}else g=null;g=null==(f=g)?void 0:f.el();f=null==(e=b.Gc())?void 0:_.Xg(e,5);if(g){e=_.vh(g,3)||null;break a}if(f){e=new _.uh(f,3);break a}}e=null}if(e)return e;if(null!==c&&uIm(a.oa,c))return _.vh(a.Wua()||void 0,3)||null;_.mb(Error("mm"));return null},HIm=function(a,b,c){try{var d,e,f=(null==(d=eIm(c))?void 0:_.F(d,5))||(null==b?void 0:null==(e=b.Gc())?void 0:_.Xg(e,5)),g=c.Vk();b=function(q){return Array.from(a.window.zd().querySelectorAll(q))};
 * var k=function(q,t){if(!q||!t)return!1;var v=q.dataset.ved===t;q=0<q.querySelectorAll('[data-ved="'+t+'"]').length;return v||q},l=b('[data-docid="'+g+'"]').filter(function(q){return k(q,f)});0===l.length&&(l=b("[jsdata]").filter(function(q){if(q&&g){var t;var v=null==q?void 0:null==(t=q.getAttribute("jsdata"))?void 0:t.includes(g);q=0<q.querySelectorAll('[jsdata="'+g+'"]').length;v=v||q}else v=!1;return v}).filter(function(q){return k(q,f)}));if(0===l.length){var n=a.Mb("dn277e").first()||a.getRoot();
 * l=b('[data-tbnid="'+g+'"]').filter(function(q){return!n.el().contains(q)})}return 1===l.length?l[0]:null}catch(q){return null}},IIm=function(a,b,c,d){var e,f,g,k,l,n,q,t,v,x,A;return _.Ch(function(E){switch(E.oa){case 1:e=_.OB(b);switch(d){case 1:case 2:case 6:case 5:case 8:case 9:case 10:return E.Hb(2)}E.Hb(3);break;case 2:return f=GIm(a,b),k="string"===typeof(null==(g=f)?void 0:g.vS)?new _.sh(f.vS):void 0,l=b.Vk(),n={replace:!0,RHc:!0,YF:c,yd:f,wd:k,OGa:!1},(q=_.Rfc(a.Dh))?(n.e1=l,n.Kt=q):(n.VZ=
 * l,n.RT=null),E.yield(a.Dh.Km(n),4);case 4:E.Hb(3);break;case 3:if(1===(null==(t=e)?void 0:t.getType())||9===(null==(v=e)?void 0:null==(x=v.Gc())?void 0:_.Hk(x,6))){var H=a.Dh,L=b.Vk();H.tb=L;if(a.g_||a.O5)H=HIm(a,e,b),a.Dh.Ma=H}(a.g_||a.O5)&&23===(null==(A=e)?void 0:A.getType())&&(H=HIm(a,e,b),a.Dh.Ma=H);"scrollRestoration"in a.window.get().history&&(a.window.get().history.scrollRestoration="auto");_.hi(E)}})},JIm=function(a){switch(a){case 1:case 2:case 5:case 6:case 8:case 9:return 3;case 0:return 5;
 * case 7:return 4;default:return 1}},KIm=function(a){switch(a){case 1:case 2:return 21;case 6:case 5:case 0:return 3;case 8:case 9:return 5;case 3:return 26;default:return 1}},LIm=function(a){return _.th(_.sj(2===a||5===a||8===a?"aIGgTb":"Ni5xnf")||null,KIm(a))},MIm=function(a,b,c,d){if(1===b||6===b||9===b||2===b||5===b||8===b)if(c){c=a.Hd.Md(function(){return a.Rb.Kc(1===b||6===b||9===b?BIm:CIm,{pF:d})},{yd:c},!1);var e=_.th(c,KIm(b))}else e=LIm(b);return e||null},NIm=function(a,b,c,d){var e=GIm(a,
 * b),f,g=(null==(f=b.Xk())?void 0:_.Ws(f))||null;f=a.wk;var k=b.Vk();(f=f.oa.get(k))&&f.Ua.resolve({ogc:c,pF:g?g:7});g=MIm(a,c,e,g);var l;b=null==(l=_.OB(b))?void 0:l.Gc();c=_.iIm(b?_.pWc(b):null,JIm(c));d instanceof _.wUb?(d.Jr=c,g&&(d.wd=g),e&&(d.yd=e),_.BUb(a.Hd,d)):g&&_.Vv(a.Jb,{wd:g,Jr:c,BK:_.fIm()})},OIm=function(a,b,c,d){var e=_.OB(b),f;if(1===(null==e?void 0:e.getType())||9===(null==e?void 0:null==(f=e.Gc())?void 0:_.Hk(f,6))){c=(new DIm).setPosition(c);f=(0,_.$cb)();c=_.ud(c,_.ge,5,f);a:switch(d){case 1:case 2:case 6:case 5:case 8:case 9:d=
 * !0;break a;default:d=!1}d=_.xg(c,7,d);var g,k;(c=null==e?void 0:null==(g=e.Gc())?void 0:null==(k=_.Ln(g))?void 0:k.Cc())&&_.Hg(d,1,c);(g=b.Vk())&&_.Hg(d,3,g);var l,n;(e=null==e?void 0:null==(l=e.Gc())?void 0:null==(n=l.getExtension(_.Qg))?void 0:n.Zq())&&_.Hg(d,2,e);var q;b=(null==(q=b.Xk())?void 0:_.Ws(q))||7;q=_.Pg(_.ipg(new _.hpg,b),EIm,d);a.ah.fetch(_.kpg.Qc(q))}},PIm=function(a){this.Ja=_.r(a)};_.D(PIm,_.u);_.h=PIm.prototype;_.h.Jj=function(){return _.F(this,2)};
 * _.h.S8b=function(a){_.Hg(this,2,a)};_.h.pjb=function(){return _.Ag(this,2)};_.h.Ng=function(){return _.Xk(this,2)};_.h.czb=function(){return _.Sg(this,3)};_.QIm=function(){var a=new PIm;return _.xg(a,3,!0)};PIm.prototype.ub="ZEIdFc";var RIm=_.T("eeNvKc");var SIm;SIm=["sG7ZCe","CGzTgf","R5S48d"];_.TIm=function(a){var b=_.Wu(a.find(".tvh9oe"));a=[];b=_.Ub(b);for(var c=b.next();!c.done;c=b.next()){c=c.value;var d=SIm.indexOf(c.getAttribute("jsname")||"");-1!==d&&(a[d]=c)}this.oa=[_.Hq(a[0]),_.Hq(a[1]),_.Hq(a[2])];this.DHb()};_.h=_.TIm.prototype;_.h.DHb=function(){};_.h.Cu=function(){return this.oa[0]};_.h.current=function(){return this.oa[1]};_.h.next=function(){return this.oa[2]};_.h.map=function(a){return this.oa.map(a)};
 * _.UIm=function(a,b,c){a.oa.forEach(function(d,e){return void c(d,b[e],e)})};_.TIm.prototype.WGb=function(a){var b=this,c=this.map(function(e){return e.children()}),d=this.map(_.kIm);_.UIm(this,a,function(e,f,g){var k=null===f?-1:d.indexOf(f);-1===k?(e.empty(),e.setData("tbnid",null)):g!==k&&(k=c[k])&&(k.remove(),e.empty(),e.append(k),b.oa[g].setData("tbnid",null),e.setData("tbnid",f))})};var VIm=function(a,b,c){c=void 0===c?!1:c;_.UIm(a,b,function(d,e,f){d.setStyle("display",!e||1!==f&&c?"none":"block")})};
 * _.TIm.prototype.aKb=function(a,b,c){var d,e;return _.Ch(function(f){if(1==f.oa)return a.empty(),d=a,e=d.append,f.yield(c,2);e.call(d,f.Aa);a.setData("tbnid",b);_.hi(f)})};_.TIm.prototype.fMa=function(){};_.TIm.prototype.mSa=function(){return!1};var WIm,XIm,YIm,ZIm,bJm,cJm;WIm=[18,22,27,28,29,38];XIm=["MFS"];YIm=null;ZIm=900;_.$Im=!1;_.aJm=!1;bJm={Escape:27,ArrowRight:39,ArrowLeft:37};cJm=[["H9tDt",_.qdb],["e1LTt",null]];
 * _.T7=function(a){_.S7.call(this,a.Oa);var b=this;this.Jh=this.Ck=this.As=this.ue=null;this.mb=this.tb=-1;this.EF=[];this.Lb=-1;this.k5=0;this.Qb=!1;this.Fa=this.yP=this.pia=0;this.Dd=!0;this.Ot=!1;this.Jd=this.Oh=this.Ic=null;this.xd=this.yc=this.I7=this.xc=this.Xc=this.rb=0;this.Rq=this.oia=!0;this.Tg=!1;this.Gj=!0;this.D7=!1;this.Cb=this.startOffset=this.Ua=0;this.Cja=!1;this.Zk=this.xi=null;this.Xl=!1;this.EI=!0;this.Hf=this.Sb=this.AP=!1;this.j9=0;this.zF=null;this.JA=!1;this.Be=this.Ya=0;this.Qp=
 * this.Ia=this.state=null;this.tf=!1;this.zr=a.service.wV;this.Qn=a.service.share;this.OG=a.service.KU;this.Nm=a.service.viewport;this.Nua=a.service.visualViewport;this.fD=a.service.K8a;this.c3=a.service.c3;this.ZR=a.service.Np;this.Sf=a.service.navigation;this.B9=a.service.B9;this.Ck=a.Df.fMc;this.FW=this.Mb("dn277e").first()||this.getRoot();this.w9=this.Mb("xFKZqd");this.Pea=this.Dh.Pea();(this.Noa=this.Dh.Noa())&&mIm(this.B9);this.wb=this.Ta("To2LVe");this.Aa=new _.TIm(this.wb);var c=this.Mb("bITJm").first();
 * c&&_.A8c(c.el())&&this.EF.push(c.Bb());(c=this.FW.closest(_.uq("Sva75c")).first())&&_.A8c(c.el())&&(c=c.Bb().querySelector('[jsname="ootzjb"]'),_.A8c(c)&&this.EF.push(c));this.Qb="rtl"!==_.ep(this.window.zd().documentElement,"direction");this.state=0;this.uQa=a.service.Or;this.Yf=a.service.focus;this.nY=_.Tu(this.uQa.get("z1MgYd"));this.s2=new Set;this.t2=new Set;this.HX=new Set;var d;this.Psb=null!=(d=_.Mg((0,_.iu)(),129))?d:100;a=this.FW.el();_.bv(this).listen(a,"touchstart",function(f){return void dJm(b,
 * f)},{passive:!1});_.bv(this).listen(a,"touchmove",function(f){var g=f.Ue,k=g.touches[0];b.Ot=!1;if(0>(null==k?void 0:k.clientX)||16>=(b.Ic||0))b.Ot=!0,eJm(b);else if(1>g.touches.length&&!b.oa.aH||b.oa.Aa)b.Ic=null,b.Oh=null,b.oa.Aa||(b.oa.Ooa=!1),b.Qj();else if(null===b.Ic&&k&&dJm(b,f),2===b.state)g.preventDefault();else{k=g.touches[0].clientX-(b.Ic||0);var l=g.touches[0].clientY-(b.Oh||0);0===b.Jd&&(1.5<=Math.abs(k/l)?6<=Math.abs(k)&&(b.Jd=2,b.oa.Ooa=!0):1.5<=Math.abs(l/k)&&(b.Jd=1));f=f.Ue.timeStamp;
 * switch(b.Jd){case 2:fJm(b,g,f);break;case 1:gJm(b,g.touches[0].clientY-(b.Oh||0),f)||g.preventDefault();break;case 0:g.preventDefault()}}},{passive:!1});_.bv(this).listen(a,"touchend",function(f){f=f.Ue;if(0===f.touches.length)if(b.oa.Aa||null===b.Ic)b.Ic=null,b.Oh=null;else if(f=f.timeStamp,b.Ic=null,b.Oh=null,1===b.state)switch(b.Jd){case 2:hJm(b,f);break;case 1:iJm(b,f)}},{passive:!1});_.bv(this).listen(a,"touchcancel",function(f){0===f.Ue.touches.length&&eJm(b)},{passive:!1});_.bv(this).listen(this.window.zd().body,
 * "keydown",function(f){return void jJm(b,f)});this.window.zd().body.style.opacity="";_.zh.broadcast(this.window.zd(),_.Idj,!0);kJm(this);var e=_.zh.listen(this.window.zd().body,_.URb,function(){b.ria()});this.addOnDisposeCallback(function(){_.zh.Dg(e)});this.ue=_.Jbl.new({zq:this,window:this.window.get()});this.KT();this.Pea&&(a=this.Na(),0<a.length&&this.qVa(a[0]));this.g_=_.$Im;if(this.O5=_.aJm)this.Gj=!1};_.D(_.T7,_.S7);
 * _.T7.Ka=function(){return{service:{K8a:_.K7,Or:_.vu,focus:_.wB,KU:_.i2,wV:_.j2,share:_.apd,visualViewport:_.YEm,viewport:_.Gv,c3:_.tic,Np:_.Kv,navigation:_.QG,B9:_.mSb},Df:{fMc:"Na3C1e"}}};_.h=_.T7.prototype;_.h.KT=function(){};_.h.JHa=function(){};_.h.kxb=function(){var a,b;return null!=(b=null==(a=this.Qp)?void 0:a.querySelector('[jsname="zccVWc"]'))?b:this.Qp};_.h.QDb=function(){var a=this;return _.Ch(function(b){a.HF();_.hi(b)})};
 * _.h.qGb=function(){var a=this,b;return _.Ch(function(c){return U7(a,a.mb)?c.yield(null==(b=a.ue)?void 0:b.AGb(),0):c.Hb(0)})};_.h.Oua=function(){var a=this,b;return _.Ch(function(c){if(1==c.oa)return c.yield(a.Eq(),2);b=c.Aa;return b instanceof _.PB?c.yield(b.Oua(),0):c.Hb(0)})};_.h.EB=function(){return this.zr.EB(this.getRoot().el())};
 * var lJm=function(a,b){_.V7(a,"PgO4Pc").toArray().forEach(function(c){c.contains(b.target)&&(a.xi=c)})},nJm=function(a,b){a.getRoot().find(".QbMJkd-UUyOHe-eteedb").toArray().forEach(function(c){c.contains(null==b?void 0:b.target)&&!mJm(a,b,new _.Dq(c))&&(a.Zk=c)})};_.T7.prototype.yF=function(){return _.Ch(function(a){_.hi(a)})};_.T7.prototype.tia=function(){return _.Ch(function(a){_.hi(a)})};_.T7.prototype.Za=function(){var a;return(null==(a=_.V7(this,"P7VTze"))?void 0:a.Bb())||this.window.zd().documentElement};
 * _.T7.prototype.Pn=function(){var a=this.Za(),b;(null==(b=this.Aja)?void 0:b.h8)!==a&&(this.Aja={h8:a,Xg:_.Zic(a)});return this.Aja.Xg};
 * var pJm=function(a,b,c){var d,e,f,g;return _.Ch(function(k){if(1==k.oa){var l=a.oa;l.Na=b;l=l.QM();d=l[b];e=l;f=d;g=e;a.tb=a.Qb?b-1:b+1;a.mb=a.Qb?b+1:b-1;f&&(a.Ia=f.Vk());if(a.Ia){l=a.wk;var n=a.Ia;_.ugc.has(c)&&_.xgc(l,n,!1)}return k.yield(oJm(a,c),2)}f&&(_.zh.broadcast(a.getRoot().el(),_.ijc,a.Ia,KIm(c)),_.zh.broadcast(a.getRoot().el(),RIm,a.Ia,KIm(c)),3===c&&_.mum.oa[a.Ia]&&a.pta(),a.uia(a.Ia));a.Ma+3>=g.length&&_.zh.broadcast(a.window.zd().body,_.Jsm,wIm(a.oa));_.hi(k)})};_.T7.prototype.uia=function(){};
 * _.T7.prototype.Qx=function(){return!1};
 * var qJm=function(a,b,c){c=void 0===c?!0:c;a.yP=b;_.W7(a.wb.Bb(),b,0);a.wb.el().classList.toggle("Fx8vcb",0!==b);for(var d=_.Ub(a.EF),e=d.next();!e.done;e=d.next())_.W7(e.value,b,0);if(c){b=_.dj(b/a.EB().width,-1,1);var f;null==(f=a.Ck)||f.seekTo(!0,a.Ma-b,a.Na().length)}},rJm=function(a,b){a.Fa=b;_.W7(a.wb.Bb(),0,b);a.wb.el().classList.toggle("Fx8vcb",0!==b)},sJm=function(a,b){a.Fa=b;if(_.$Im){var c=a.wb.Bb();if(!a.tf){"scrollRestoration"in a.window.get().history&&(a.window.get().history.scrollRestoration=
 * "manual");a.Qp&&(a.i6(),a.Qp.style.opacity="0");var d=a.cZ().Bb();if(d){ZIm=a.window.get().innerHeight||900;d.closest("scrolling-carousel")&&d.scrollIntoView({inline:"start"});try{YIm=_.ybl(d)}catch(f){}YIm&&(d=Number(getComputedStyle(a.getRoot().el()).zIndex),d=isNaN(d)?1020:d,YIm.style.zIndex=""+(d+1),YIm.style.opacity="1",YIm.style.transformOrigin="top");c.style.transformOrigin="top";d=_.Ub([a.Aa.Cu(),a.Aa.next()]);for(var e=d.next();!e.done;e=d.next())e=e.value.Bb(),e.style.display="none",e.style.opacity=
 * "0",e.style.visibility="hidden";a.tf=!0}else a.tf=!0,a.Qp&&(a.Qp.style.opacity="1")}d="translate(0, "+b+"px)";c.style.transform=d;YIm&&(c.style.opacity=""+(1-b/(100/3)),YIm.style.transform=d+" scale("+Math.max(.5,1-b/ZIm)+")")}else _.W7(a.wb.Bb(),0,b);a.wb.el().classList.toggle("Fx8vcb",0!==b);c=1-Math.min(Math.abs(b),100)/2/100;a.getRoot().setStyle("background","none");a.w9.setStyle("opacity",c);a=_.Ub(a.EF);for(c=a.next();!c.done;c=a.next())_.W7(c.value,0,b)},U7=function(a,b){return 0<=b&&b<a.Na().length};
 * _.T7.prototype.FF=function(){if(this.Tg){var a=this.EB().height+10;_.UIm(this.Aa,[-a,0,a],function(b,c){_.W7(b.Bb(),0,c)})}else a=this.EB().width,this.Aa.current().Tc("JHumDe")&&(a-=40),a=(this.Qb?1:-1)*(a+10),_.UIm(this.Aa,[-a,0,a],function(b,c){_.W7(b.Bb(),c,0)})};
 * _.T7.prototype.lia=function(){var a=0;this.Dh.iDa&&(a=3);var b=vIm(this.oa,this.oa.Fa||"");if(0<=b){var c=null;this.Aa.current().children().get(0)&&(c=this.Na()[b]);var d;if(c=null==c?void 0:null==(d=c.Xk())?void 0:_.Ws(d)){if(d=this.oa.oa,0<d.indexOf("-")&&(d=d.substring(0,d.indexOf("-"))),WIm.includes(c)||XIm.includes(d))this.D7=!0}else this.D7=!1;tJm(this,b,a)}else a="In render no metadata with docid "+(this.oa.Fa||null),(b=_.sg())&&b.oa(Error(a),a+" (results.length='"+(this.Na()?this.Na().length:
 * "null")+"\n              , historyParam=' + "+_.No(this.oa.getData("hp"))+"\n              , initialStreamId=' + "+(this.oa.Fa||null)+"\n              , query=' + "+this.oa.getQuery()+")")};_.T7.prototype.zP=function(){};_.T7.prototype.Bu=function(a){var b=this;return _.Ch(function(c){switch(c.oa){case 1:if(b.s2.has(a)){c.Hb(0);break}b.s2.add(a);_.Dh(c,3);return c.yield(_.Tol(b.OG,a),5);case 5:_.ji(c,4);break;case 3:_.Eh(c);case 4:_.oh(function(){return b.s2.delete(a)},5E3),_.hi(c)}})};
 * _.uJm=function(a,b,c,d){d=void 0===d?!1:d;var e=b.Vk();a.t2.has(e)||(a.t2.add(e),c&&_.zh.broadcast(c,_.Xyg,{SU:d}),_.oh(function(){return a.t2.delete(e)},5E3))};_.T7.prototype.wia=function(){};_.vJm=function(a){var b,c,d,e;return null!=(e=null==(b=_.OB(a))?void 0:null==(c=b.Gc())?void 0:null==(d=_.Ln(c))?void 0:d.Cc())?e:null};_.T7.prototype.MQa=function(){U7(this,this.mb)&&tJm(this,this.Ma+1,5)};_.T7.prototype.UQa=function(){U7(this,this.tb)&&tJm(this,this.Ma-1,6)};
 * _.T7.prototype.LQa=function(a){a=a.data;this.Ma!==a&&0<=a&&a<this.Na().length&&tJm(this,a,10)};
 * var tJm=function(a,b,c){var d,e,f,g,k;return _.Ch(function(l){switch(l.oa){case 1:if(!a.Dh.rEb()){l.Hb(2);break}return l.yield(a.Dh.Wfa(),3);case 3:return l.yield(tJm(a,b,c),4);case 4:return l.return();case 2:return qJm(a,0,!1),null==(d=a.Ck)||d.Aa(!0,b,a.Na().length),a.xia(),l.yield(pJm(a,b,c),5);case 5:a.Aa.mSa()||a.FF();if(a.Ia){var n=a.wk,q=a.Ia;a.getRoot();var t;null!=(t=n.oa.get(q))&&t.SU&&n.oa.has(q)}e=a.Na();f=e[b];return l.yield(IIm(a,f,a.oa.YF,c),6);case 6:a.window.zd().dispatchEvent(new CustomEvent("viewerUpdated",
 * {detail:{id:wIm(a.oa),k:b,vhid:null==(g=f)?void 0:g.Vk(),vid:a.oa.oa}}));wJm(a,b,c);a.yF();if(_.$Im||_.aJm)a.Qp=a.Dh.Ma,a.g6();return l.yield(a.tia(null!=(k=a.Qp)?k:void 0),7);case 7:n=a.Aa.current(),(n=_.Zu(a,n,"H9tDt").el())&&(n=(0,_.Yp.pyb)(n))&&_.zp(window,"attn_viewer_open",n),_.hi(l)}})},wJm=function(a,b,c){var d,e,f,g,k;_.Ch(function(l){if(1==l.oa)return d=a.Na(),e=d[b],k=(g=null==(f=a.Aa.current().children().filter(function(n){return!!n["__deferred-log"]}).first())?void 0:f.el())&&g["__deferred-log"],
 * NIm(a,e,c,k),g&&(g["__deferred-log"]=void 0),l.yield(a.oa.h6a().wait(),2);OIm(a,e,b,c);_.hi(l)})};_.T7.prototype.ria=function(){_.Vv(this.Jb,{wd:_.th(this.SDa().el(),26)})};_.T7.prototype.Xua=function(){this.Pea||this.oa.Aa||(_.Ljc(this.window.zd()),_.Sg((0,_.iu)(),92)?this.Dh.Km({}):nIm(this.Dh),xJm(this),_.zh.broadcast(this.getRoot().el(),_.ijc,null))};
 * var jJm=function(a,b){var c,d,e,f,g;return _.Ch(function(k){switch(k.oa){case 1:if(!a.Dh.T5()||"INPUT"===(null==(c=a.window.zd().activeElement)?void 0:c.tagName)||"TEXTAREA"===(null==(d=a.window.zd().activeElement)?void 0:d.tagName)||a.Qx())return k.return();e=bJm[b.key]||b.keyCode;if(27!==e){k.Hb(2);break}f=_.V7(a,"xl07Ob").el();if(!f){k.Hb(3);break}return k.yield(a.Kf(f),4);case 4:if(g=k.Aa,g.isOpen)return g.Q1(),k.return();case 3:return yJm(a,5),k.return();case 2:if(a.oia){if(37===e&&!(b.ctrlKey||
 * b.altKey||b.shiftKey||b.metaKey)&&U7(a,a.tb))return a.Qra(),tJm(a,a.tb,a.Qb?9:8),b.preventDefault(),k.return();if(39===e&&!(b.ctrlKey||b.altKey||b.shiftKey||b.metaKey)&&U7(a,a.mb))return a.Qra(),tJm(a,a.mb,a.Qb?8:9),b.preventDefault(),k.return()}_.hi(k)}})};_.T7.prototype.handleResize=function(){var a=this;this.k5||(this.k5=setTimeout(function(){var b=a.EB().width;b!==a.pia&&(a.FF(),a.pia=b);a.k5=0}))};
 * var oJm=function(a,b){var c,d,e,f,g,k,l;return _.Ch(function(n){c=a.Na();d=a.Aa.map(function(q,t){q=a.Ma-1+t;return U7(a,q)?c[q]:null});e=jIm(d,function(q){var t;return null!=(t=null==q?void 0:q.Vk())?t:null});a.Aa.WGb(e);a.As=null;f=jIm(d,function(q){return!!q});g=a.nY;VIm(a.Aa,f,g);a.Aa.mSa()&&a.FF();k=[];l=a.Aa.map(lIm);_.UIm(a.Aa,d,function(q,t,v){t&&(v=l[v],0===v?(v=t.Vk(),k.push(a.Aa.aKb(q,v,zJm(a,t)).then(function(){return void AJm(a,q,t)}))):2===v&&AJm(a,q,t))});a.Ia&&(pIm(a.wk,a.Ia),rIm(a.wk,
 * a.Ia,a.Aa.current().el()),oIm(a.wk,b,a.Ia,a.Aa.current().el()));return n.yield(Promise.all(k),0)})},AJm=function(a,b,c){if(c.Vk()===a.Ia){b=b.Bb();_.zh.broadcast(b,_.ijc,a.Ia);a.JHa();a.pGb(c);a.qVa(c);a.Bja();var d;null==(d=a.Jh)||d.mb(b);var e;null==(e=a.Jh)||e.rb(eIm(c));var f;null==(f=a.Jh)||f.wb()}},zJm=function(a,b){var c,d,e,f,g,k,l;return _.Ch(function(n){if(1==n.oa)return c={yd:_.vh(a.Wua()||void 0,3),BK:_.fIm()},d=eIm(b),f={Xa:b.HJ(),isActive:!1,ambientParams:_.QIm(),imageHeight:null!=(e=
 * _.Qo(a.getData("ih")))?e:void 0,Ah:d},n.yield(AIm(a.Aab,f,c),2);g=n.Aa;k=g.output;l=g.oa;k["__deferred-log"]=l;return n.return(k)})};_.T7.prototype.Om=function(){return!this.Za().scrollTop};
 * var dJm=function(a,b){var c=b.Ue;if(a.oa.Aa)a.Ic=null,a.Oh=null,a.Qj();else if(!(a.oa.aH||1<c.touches.length)){var d,e,f,g=(null==(d=a.ue)?0:d.Ltb())?null!=(f=null==(e=a.ue)?void 0:e.YAb())?f:0:0;d=c.touches[0];a.Ot=!1;a.Ic=d.clientX-g;a.Oh=d.clientY;a.Jd=g?2:0;a.I7=c.timeStamp;a.yc=g;a.xd=c.timeStamp;a.xi=null;a.Zk=null;a.Xl=!1;nJm(a,b);a.Cja=!a.Zk&&mJm(a,b);lJm(a,b);a.Ou();2===a.Jd&&(a.oa.Ooa=!0,fJm(a,c,c.timeStamp))}};_.T7.prototype.Ou=function(){this.Dd=this.Om()};
 * var fJm=function(a,b,c){var d=b.touches[0].clientX-(a.Ic||0);if(1!==a.state)if(a.xi){var e=a.Qb?0>d:0<=d,f=Math.abs(a.xi.scrollLeft),g=Math.round(a.xi.scrollWidth-a.xi.clientWidth-f);if(!(1>=f&&!e||1>=g&&e)){a.Xl=!0;return}}else if(a.Zk){var k=a.Qb?0>d:0<=d,l=!0,n=a.Zk.clientWidth;a.Zk.childNodes.forEach(function(q){_.A8c(q)&&(q=q.getBoundingClientRect(),!k&&1>q.left?l=!1:k&&q.right>n+1&&(l=!1))});if(l)a.Xl=!1;else{a.Xl=!0;return}}a.Cja||a.Xl||BJm(a,d,c)||b.preventDefault()},BJm=function(a,b,c){if(!a.Rq)return!0;
 * if(0===a.state){if(!a.Aa.current().Tc("JHumDe")){var d=-a.wb.el().getBoundingClientRect().top;a.Aa.Cu().setStyle("top",d+"px");a.Aa.next().setStyle("top",d+"px")}a.state=1}d=a.Aa.current().Bb().clientWidth+10;var e=(0<b?1:-1)*Math.sqrt(Math.abs(b));b=Math.max(b,U7(a,a.mb)?-d:e);b=Math.min(b,U7(a,a.tb)?d:e);a.Ua=(b-a.yc)/(c-a.xd+1);qJm(a,b);a.yc=b;a.xd=c;CJm(a,a.Qb?0>b:0<=b);return!1};
 * _.T7.prototype.i6=function(){!this.Qp||_.qbl(this.Qp)?this.fD.Aa(_.Sg((0,_.iu)(),31)?this.Ia:null):(this.Qp.scrollIntoView({inline:"nearest",block:"nearest"}),xIm(this.fD))};
 * var CJm=function(a,b){var c=!b,d=a.Na(),e=a.Ma,f=a.Aa.Cu(),g=a.Aa.next();b&&d.length-1>=e+1&&DJm(a,d[e+1],g);c&&0<=e-1&&DJm(a,d[e-1],f)},DJm=function(a,b,c){var d=_.vJm(b);d&&(a.Bu(d),a.wia(b));_.uJm(a,b,c.Bb(),!0)},gJm=function(a,b,c){if(a.Gj&&!_.aJm){if(_.Sg((0,_.iu)(),37)&&a.Gj&&!a.oa.aH&&!a.Pea&&0<b&&a.Dd&&0<=a.Fa){a.oa.aH=!0;a.state=1;_.yIm(a.fD,!0);a.fD.Gk();_.$Im||a.fD.Aa(_.Sg((0,_.iu)(),31)?a.Ia:null);var d;null==(d=a.Ck)||d.Aa(!1,a.Ma,a.Na().length)}if(a.oa.aH)return sJm(a,Math.max(0,b)),
 * a.Ua=(b-a.yc)/(c-a.xd+1),a.yc=b,!1;a.pCb(b,c)}else if(a.Tg){0===a.state&&(a.state=1);d=a.Aa.current().Bb().clientHeight+10;var e=(0<b?1:-1)*Math.sqrt(Math.abs(b));b=Math.max(b,U7(a,a.mb)?-d:e);b=Math.min(b,U7(a,a.tb)?d:e);a.Ua=(b-a.yc)/(c-a.xd+1);rJm(a,b);a.yc=b;a.xd=c;CJm(a,0>b);return!1}a.xd=c;return!0},hJm=function(a,b){a.oa.Ooa=!1;var c=a.yP,d=a.Aa.current().Bb().clientWidth;b=Math.abs(c/(b-a.I7+1));(c>d/4&&-.2<a.Ua||0<c&&.2<a.Ua)&&U7(a,a.tb)?(a.Cb=d+10,a.Lb=a.tb,EJm(a,b)):(c<-d/4&&.2>a.Ua||0>
 * c&&-.2>a.Ua)&&U7(a,a.mb)?(a.Cb=-(d+10),a.Lb=a.mb,EJm(a,b)):eJm(a)};_.T7.prototype.II=function(){var a=this,b,c;return _.Ch(function(d){switch(d.oa){case 1:return _.Dh(d,2),_.$Im?d.yield(null==(b=a.ue)?void 0:b.Aa(a.Qp),5):d.yield(a.IF(),5);case 5:_.ji(d,3);break;case 2:c=_.Eh(d),_.mb(Error("nm",{cause:c}));case 3:a.state=0,a.oa.aH=!1,a.getRoot().setStyle({position:""}),yJm(a,21),_.hi(d)}})};_.T7.prototype.CQa=function(){return _.Ch(function(a){_.hi(a)})};
 * var iJm=function(a,b){var c,d,e,f,g,k;_.Ch(function(l){if(!a.Gj||_.aJm)return a.Tg&&(a.state=0,c=a.Fa,d=a.Aa.current().Bb().clientHeight,e=Math.abs(c/(b-a.I7+1)),(c>d/4&&-.2<a.Ua||0<c&&.2<a.Ua)&&U7(a,a.tb)?(a.Cb=d+10,a.Lb=a.tb,FJm(a,e)):(c<-d/4&&.2>a.Ua||0>c&&-.2>a.Ua)&&U7(a,a.mb)?(a.Cb=-(d+10),a.Lb=a.mb,FJm(a,e)):eJm(a)),l.Hb(0);a.oa.aH=!1;f=a.Fa;g=!1;g=-1>a.Ua?!1:1<a.Ua?!0:100<f;k=!1;g&&a.D7&&(g=!1,k=!0);return k?(a.state=0,a.oa.aH=!1,a.getRoot().setStyle({position:""}),l.yield(a.Dh.Wfa(),0)):g?
 * l.yield(a.II(),0):l.yield(a.cBa(),0)})};_.h=_.T7.prototype;_.h.cBa=function(){var a=this;return _.Ch(function(b){return b.yield(a.Qj(),0)})};_.h.V4=function(){var a=_.V7(this,"figiqf").el(),b=_.V7(this,"St5Dhe").el();a&&b&&(this.j9=52+a.clientHeight+b.clientHeight);return this.j9};_.h.uxb=function(){var a=_.V7(this,"figiqf").el();return a?52+Math.round(a.clientHeight/2):0};_.h.vZ=function(){return 0};_.h.qVa=function(){};_.h.pCb=function(){};_.h.zha=function(){};_.h.pLa=function(){};_.h.dha=function(){};
 * _.h.pta=function(){};_.h.nLa=function(){};_.h.cha=function(){};_.h.XJa=function(){};_.h.YJa=function(){};_.h.ZBa=function(){};_.h.Rxa=function(){return!1};_.h.Qra=function(){this.YJa();this.XJa()};_.h.b9=function(){};_.h.yMb=function(){};_.h.pGb=function(){};_.h.qKa=function(){};_.h.fLa=function(){return!1};_.h.f3a=function(){};_.h.N3a=function(){};_.h.DZa=function(){};_.h.Doa=function(){return!1};_.V7=function(a,b){return _.Xu(a.Aa.current(),b)};_.T7.prototype.Qa=function(){return null};
 * _.T7.prototype.zQa=function(){return{element:this.Qp}};_.T7.prototype.Qj=function(){var a=this,b;return _.Ch(function(c){if(1==c.oa){if(0===a.Fa&&a.oa.Aa)return c.return();a.oa.aH=!1;return c.yield(GJm(a),2)}null==(b=a.Ck)||b.Aa(!0,a.Ma,a.Na().length);_.Mj(function(){return _.Ch(function(d){a.oa.aH=!1;a.state=0;sJm(a,0);a.getRoot().setStyle({position:"","padding-top":""});_.$Im&&a.HF();_.hi(d)})});_.hi(c)})};var yJm=function(a,b){var c=a.SDa();c&&_.Vv(a.Jb,{wd:_.th(c.el(),b)});a.Xua()};_.h=_.T7.prototype;
 * _.h.SDa=function(){return _.V7(this,"tqp7ud")};_.h.Fwc=function(a){var b=a.data;a=b.timeStamp;var c=b.offset;b=c.x;c=c.y;b?BJm(this,b,a):c&&gJm(this,c,a)};_.h.Gwc=function(a){var b=a.data;a=b.timeStamp;b=b.offset;var c=b.y;b.x?hJm(this,a):c&&iJm(this,a)};_.h.v3b=function(a){a=a.data;this.oa.MLb(a);HJm(this);this.wb.setStyle("touch-action",a?"none":"");_.zh.broadcast(this.Ta("CGzTgf").el(),_.njc,a)};_.h.Sxc=function(a){this.oia=a.data};_.h.Rxc=function(a){if(this.Rq=a.data)this.Tg=!1};
 * _.h.Uxc=function(a){if(this.Tg=a.data)this.Rq=!1};_.h.Txc=function(a){this.Gj=a.data};
 * var HJm=function(a){var b=!a.oa.Aa;if(b!==a.EI){var c=a.SDa();c.el()&&(b&&c.show(),(new _.NB).step({id:"bFvuJb",duration:300,curve:"ease-in-out",delay:.1,element:c.el(),style:{opacity:b?1:.001},after:function(){b||a.EI||c.Ac()}}).start(),a.EI=b)}},eJm=function(a){a.Cb=0;a.Lb=a.Ma;EJm(a);a.Tg&&FJm(a)},EJm=function(a,b){a.state=2;a.startOffset=a.yP;a.Ya=0;a.Be=b?Math.min(Math.abs(a.Cb-a.startOffset)/b,100):100;IJm(a,0)},FJm=function(a,b){a.state=2;a.startOffset=a.Fa;a.Ya=0;a.Be=b?Math.min(Math.abs(a.Cb-
 * a.startOffset)/b,100):100;JJm(a,0)},IJm=function(a,b){a.Ya||(a.Ya=b);b=1-Math.pow(1-Math.min((b-a.Ya)/a.Be,1),3);qJm(a,a.startOffset+b*(a.Cb-a.startOffset));var c=a.window.get().requestAnimationFrame||a.window.get().webkitRequestAnimationFrame;1>b&&c?c(function(d){IJm(a,d)}):_.Mj(function(){a.oa.aH=!1;a.state=0;a.Lb===a.Ma?qJm(a,0):(a.Qra(),tJm(a,a.Lb,a.Lb===(a.Qb?a.tb:a.mb)?1:2))})},JJm=function(a,b){a.Ya||(a.Ya=b);b=1-Math.pow(1-Math.min((b-a.Ya)/a.Be,1),3);rJm(a,a.startOffset+b*(a.Cb-a.startOffset));
 * var c=a.window.get().requestAnimationFrame||a.window.get().webkitRequestAnimationFrame;1>b&&c?c(function(d){JJm(a,d)}):_.Mj(function(){a.oa.aH=!1;a.state=0;a.Lb===a.Ma?rJm(a,0):(a.Qra(),tJm(a,a.Lb,a.Lb===a.tb?1:2))})},GJm=function(a){var b=new _.pu;a.state=2;a.startOffset=a.Fa;a.Cb=0;a.Ya=0;a.Be=100;KJm(a,0,b);_.yIm(a.fD,!1);a.fD.lj();return b.promise};
 * _.T7.prototype.IF=function(){var a=new _.pu;this.state=2;this.startOffset=this.Fa;this.Cb=this.window.get().innerHeight;this.Ya=0;this.Be=100;KJm(this,0,a);return a.promise};var KJm=function(a,b,c){a.Ya||(a.Ya=b);b=1-Math.pow(1-Math.min((b-a.Ya)/a.Be,1),3);sJm(a,a.startOffset+b*(a.Cb-a.startOffset));var d=a.window.get().requestAnimationFrame||a.window.get().webkitRequestAnimationFrame;1>b&&d?d(function(e){KJm(a,e,c)}):c.resolve()};
 * _.T7.prototype.Eq=function(){var a=this;return _.Ch(function(b){if(1==b.oa)return a.As?b.Hb(2):b.yield(LJm(a),3);2!=b.oa&&(a.As=b.Aa);return b.return(a.As)})};
 * var LJm=function(a){var b,c,d,e,f,g,k,l,n,q;return _.Ch(function(t){switch(t.oa){case 1:b=a.Aa.current(),c=_.Ub(cJm),d=c.next();case 2:if(d.done){t.Hb(4);break}e=d.value;f=_.Ub(e);g=f.next().value;k=f.next().value;l=g;n=k;q=_.Zu(a,b,l).el();if(!q){t.Hb(3);break}return t.yield(n?_.bu(a,q):a.Kf(q),6);case 6:return t.return(t.Aa);case 3:d=c.next();t.Hb(2);break;case 4:return t.return(null)}})};_.T7.prototype.Bja=function(){var a=this.Aa.current();_.CB(this.Yf,a,void 0,{preventScroll:!0})};
 * _.T7.prototype.xia=function(){var a=this.Aa.current();_.EB(a)};var kJm=function(a){a.Qn.lR()&&(a.Qn.UX(function(){return MJm()}),a.AP=!0,a.addOnDisposeCallback(function(){return void xJm(a)}))},MJm=function(){return _.Ch(function(a){try{return a.return(!1)}catch(b){return _.mb(new ReferenceError("om",{cause:b})),a.return(!1)}})},xJm=function(a){a.AP&&a.Qn.lR()&&(a.Qn.f0(),a.AP=!1)};_.h=_.T7.prototype;
 * _.h.Zu=function(a){var b=this,c,d,e,f,g,k;return _.Ch(function(l){if(1==l.oa)return l.yield(b.Eq(),2);if(5!=l.oa)return c=l.Aa,c instanceof _.PB?(e=null==(d=c)?void 0:d.Mb("AfqdGe").el())?l.yield(null==(f=c)?void 0:_.bu(f,e),5):l.Hb(0):l.Hb(0);g=l.Aa;return l.yield(null==(k=g)?void 0:k.Zu(a),0)})};_.h.HZa=function(){};_.h.UBa=function(){};_.h.tCa=function(){};_.h.ywc=function(){};_.h.Ptc=function(){return this.w9};_.h.Qtc=function(){return this.FW};
 * _.h.cZ=function(){var a=_.Eq(this.Aa.current(),".pT0Scc");return a.isEmpty()?_.Eq(this.getRoot(),"[jsname=YQKdAf]"):a};_.h.ZQ=function(){return this.wb};_.h.Xxb=function(){var a,b;return null!=(b=null==(a=this.Na()[this.Ma].Xk())?void 0:_.Ws(a))?b:0};_.W7=function(a,b,c){_.cp(a,"transform",b||c?"translate3d("+b+"px, "+c+"px, 0)":"")};
 * _.T7.prototype.HF=function(){if(this.tf){this.tf=!1;this.g6();this.Qp&&(this.Qp.style.opacity="1");var a=this.wb.Bb();a&&(a.style.transformOrigin="");a=_.Ub([this.Aa.Cu(),this.Aa.next()]);for(var b=a.next();!b.done;b=a.next())b=b.value.Bb(),b.style.display="block",b.style.opacity="",b.style.visibility=""}};_.T7.prototype.g6=function(){_.zbl();var a;null==(a=YIm)||a.remove();YIm=null};
 * var mJm=function(a,b,c){c=void 0===c?a.getRoot():c;return _.raa(c.find("scrolling-carousel").toArray(),c.find("g-scrolling-carousel").toArray(),c.find(".ZsmQ7d-eteedb").toArray()).some(function(d){return d.contains(b.target)})};_.T7.prototype.Yua=function(){var a=this,b;return _.Ch(function(c){if(1==c.oa)return c.yield(a.Eq(),2);b=c.Aa;return b instanceof _.PB?c.yield(b.anb(),0):c.Hb(0)})};_.U(_.T7.prototype,"Q6YbSb",function(){return this.Yua});_.U(_.T7.prototype,"MYe5Uc",function(){return this.g6});
 * _.U(_.T7.prototype,"JdBUhf",function(){return this.HF});_.U(_.T7.prototype,"MXIqkf",function(){return this.Xxb});_.U(_.T7.prototype,"xSjSX",function(){return this.ZQ});_.U(_.T7.prototype,"GEPTmf",function(){return this.cZ});_.U(_.T7.prototype,"rUm1qb",function(){return this.Qtc});_.U(_.T7.prototype,"MoDOK",function(){return this.Ptc});_.U(_.T7.prototype,"WDtm3c",function(){return this.ywc});_.U(_.T7.prototype,"ToJyDd",function(){return this.tCa});_.U(_.T7.prototype,"t7Vn4",function(){return this.UBa});
 * _.U(_.T7.prototype,"jDwqXc",function(){return this.HZa});_.U(_.T7.prototype,"geL4Eb",function(){return this.Zu});_.U(_.T7.prototype,"yBLDjf",function(){return this.xia});_.U(_.T7.prototype,"x4ag8c",function(){return this.Bja});_.U(_.T7.prototype,"iH8nrf",function(){return this.Eq});_.U(_.T7.prototype,"OcXYh",function(){return this.IF});_.U(_.T7.prototype,"IRuuWd",function(){return this.Txc});_.U(_.T7.prototype,"SSK0ve",function(){return this.Uxc});_.U(_.T7.prototype,"JcQbHe",function(){return this.Rxc});
 * _.U(_.T7.prototype,"hTA2he",function(){return this.Sxc});_.U(_.T7.prototype,"OE3eub",function(){return this.v3b});_.U(_.T7.prototype,"hGQO5e",function(){return this.Gwc});_.U(_.T7.prototype,"Cw6uhb",function(){return this.Fwc});_.U(_.T7.prototype,"ev8l7c",function(){return this.SDa});_.U(_.T7.prototype,"RLLnI",function(){return this.Qj});_.U(_.T7.prototype,"dsJZzf",function(){return this.zQa});_.U(_.T7.prototype,"L5gIMe",function(){return this.Qa});_.U(_.T7.prototype,"wxChZd",function(){return this.Doa});
 * _.U(_.T7.prototype,"A4k9Vd",function(){return this.DZa});_.U(_.T7.prototype,"Ijzr1",function(){return this.N3a});_.U(_.T7.prototype,"Jvd5u",function(){return this.f3a});_.U(_.T7.prototype,"nX61ye",function(){return this.fLa});_.U(_.T7.prototype,"pZpEZb",function(){return this.qKa});_.U(_.T7.prototype,"reKp0c",function(){return this.Qra});_.U(_.T7.prototype,"yKuxle",function(){return this.Rxa});_.U(_.T7.prototype,"KqEe0",function(){return this.YJa});_.U(_.T7.prototype,"A7vGVd",function(){return this.XJa});
 * _.U(_.T7.prototype,"D72xY",function(){return this.cha});_.U(_.T7.prototype,"Bk3dR",function(){return this.nLa});_.U(_.T7.prototype,"LTfUlb",function(){return this.pLa});_.U(_.T7.prototype,"u6eyPb",function(){return this.vZ});_.U(_.T7.prototype,"MCmM8c",function(){return this.uxb});_.U(_.T7.prototype,"PCPNZ",function(){return this.V4});_.U(_.T7.prototype,"EukRKe",function(){return this.cBa});_.U(_.T7.prototype,"AUpCvc",function(){return this.CQa});_.U(_.T7.prototype,"AOmjrc",function(){return this.II});
 * _.U(_.T7.prototype,"axxrud",function(){return this.i6});_.U(_.T7.prototype,"dqJgrd",function(){return this.Ou});_.U(_.T7.prototype,"b4iS2b",function(){return this.Om});_.U(_.T7.prototype,"mhSdVe",function(){return this.handleResize});_.U(_.T7.prototype,"qdYhxb",function(){return this.Xua});_.U(_.T7.prototype,"LvQSUe",function(){return this.ria});_.U(_.T7.prototype,"aJr3Ke",function(){return this.LQa});_.U(_.T7.prototype,"dYRl4b",function(){return this.UQa});_.U(_.T7.prototype,"awLsX",function(){return this.MQa});
 * _.U(_.T7.prototype,"ycRj9d",function(){return this.zP});_.U(_.T7.prototype,"D5BN",function(){return this.lia});_.U(_.T7.prototype,"V94cRb",function(){return this.FF});_.U(_.T7.prototype,"WFrkbb",function(){return this.Qx});_.U(_.T7.prototype,"FvSfLc",function(){return this.Pn});_.U(_.T7.prototype,"PK2OVe",function(){return this.Za});_.U(_.T7.prototype,"xd9j7b",function(){return this.yF});_.U(_.T7.prototype,"MLHG2b",function(){return this.Oua});_.U(_.T7.prototype,"CLTwce",function(){return this.qGb});
 * _.U(_.T7.prototype,"qAf8Hf",function(){return this.QDb});_.U(_.T7.prototype,"a7cIt",function(){return this.kxb});_.U(_.T7.prototype,"CNNeqb",function(){return this.JHa});_.U(_.T7.prototype,"IaQd1e",function(){return this.KT});_.ev(_.Hib,_.T7);
 * _.T7.prototype.uia=function(a){var b=this.oa;b.k_||b.oa!==_.q9a.id(1)?"regis"===this.oa.oa?(a=a.split("-"),2>a.length||_.zh.broadcast(document.body,_.PRb,a[0]+"-"+a[1])):_.zh.broadcast(document.body,_.PRb):_.zh.broadcast(document.body,_.PRb,a)};_.T7.prototype.zP=function(){var a=this.Na();if(0<this.Ma){var b=_.vJm(a[this.Ma-1]);b&&this.Bu(b)}this.Ma+1<a.length&&(a=_.vJm(a[this.Ma+1]))&&this.Bu(a)};_.U(_.T7.prototype,"ycRj9d",function(){return this.zP});
 * _.T7.prototype.Qx=function(){return null!=this.qf&&this.qf.Qx()};_.U(_.T7.prototype,"WFrkbb",function(){return this.Qx});_.T7.prototype.yF=function(){var a=this;return _.Ch(function(b){if(1==b.oa)return null!=a.qf?b.Hb(0):b.yield(_.ze(_.is,a.Ci()),3);a.qf=b.Aa;_.hi(b)})};_.U(_.T7.prototype,"xd9j7b",function(){return this.yF});
 * 
 * 
 * 
 * _.p();
 * 
 * _.VJm=function(a,b){a=a.innerWidth;a=1264>a?368:Math.min(368+a-1264,569);368<a?b.Nb("sUDUrf").Ob("WdLoq"):b.Nb("WdLoq").Ob("sUDUrf");b.setStyle("width",a+"px")};
 * _.m("ZfBJ7b");
 * var WJm,XJm,YJm,ZJm,$Jm,aKm,bKm,cKm,dKm;_.L7.prototype.Lb=_.ba(364,function(a){1>=_.xFm(this)&&a&&(a.style.height="764px")});WJm=function(a){return _.Ch(function(b){if(1==b.oa)b=b.yield(a.Ia,2);else{var c=b.return;var d,e=null!=(d=_.qSb(a))?d:a.getScope((0,_.oSb)(4));if(!e)throw Error("be");b=c.call(b,e)}return b})};
 * XJm=function(a,b,c){if(b=a.oa.get(b))if(b.Fa.resolve(c),b.Vf.start(),c=b.Vf.Aa.startTime+(_.fgc?window.performance.timeOrigin:0),null!=b.oa&&b.oa<c&&9048924E5<=b.oa?_.gB(b.Vf,"uvpovct",Math.round(b.oa-c)):b.oa=void 0,window.performance&&window.performance.now()&&_.gB(b.Vf,"ns",-1*Math.round(b.Vf.Aa.startTime)),_.gB(b.Vf,"uvpcot",0),a=a.fl.get(),a.uvplt&&b.oa&&b.Vf){if(a.uvplt.fft){var d=Math.max(a.uvplt.fft,b.oa);a.uvplt.lrt&&a.uvplt.lrt>d&&a.uvplt.lrt<c?b.Vf.oa("uvpfact",Math.round(a.uvplt.lrt-d).toString()):
 * c>d&&b.Vf.oa("uvpfact",Math.round(c-d).toString())}a.uvplt.fht&&(d=Math.max(a.uvplt.fht,b.oa),a.uvplt.lvt&&a.uvplt.lvt>d&&a.uvplt.lvt<c?b.Vf.oa("uvphact",Math.round(a.uvplt.lvt-d).toString()):c>d&&b.Vf.oa("uvphact",Math.round(c-d).toString()));a.uvplt.frz&&b.Vf.oa("uvpsrpf","1")}};YJm=function(a,b){var c=a.oa.get(b),d;null==c||null==(d=c.Vf)||null==d.Aa.startTime||(null==c?0:c.Aa)?a.oa.delete(b):(c.Aa=!0,_.hB(c.Vf,"uvphcdt"))};
 * ZJm=function(a,b){a.window.visualViewport&&a.window.visualViewport.addEventListener("resize",b)};$Jm=function(a){var b,c;return null!=(c=null==(b=a.window.visualViewport)?void 0:b.pageLeft)?c:0};aKm=function(a,b,c){return _.Ch(function(d){return d.return(_.zIm(a,function(e){return a.Hd.Md(e,c,!0)},b))})};bKm=function(a,b){var c,d;return _.Ch(function(e){_.uJm(a,a.Na()[a.Ma],a.Aa.current().Bb(),!1);null==(c=a.Jh)||c.Lb(a.cZ().Bb());return e.yield(null==(d=a.ue)?void 0:d.Fa(a.kxb(),b),0)})};
 * cKm=function(a){var b;return _.Ch(function(c){if(a.Ot||a.tf&&_.$Im)return a.HF(),c.Hb(0);a.i6();return c.yield(null==(b=a.ue)?void 0:b.Aa(a.Qp),0)})};dKm=function(a,b){a.Qp=b.element};
 * _.X7=function(a){_.Wh.call(this,a.Oa);var b=this;this.WTa=this.ZD=null;this.window=a.service.window.get();this.document=a.service.window.zd();this.chrome=a.service.chrome;this.Ym=a.service.config;this.uKa=a.service.ysa;this.MB=a.service.Z4;this.ZR=a.service.Np;this.zr=a.service.wV;this.Jb=a.service.qc;this.c3=a.service.c3;this.cJ=a.model.aG;this.Aab=a.service.yab;this.Se=a.service.Se;this.Jh=a.service.Pz;this.oe=null;this.Hd=a.service.Bd;this.fD=a.service.K8a;this.vp=a.service.stream;this.wga=a.service.E6a;
 * this.wk=a.service.wk;this.ZD=(new _.zq([this.document])).find("[jsname=Z9MBEf]").el();this.Nua=a.service.visualViewport;this.gJ=a.service.Fla;_.zh.listen(this.window.document.body,_.ylc,function(){b.ZD&&b.qFa(b.ZD,null)});_.Sg(this.Ym.oa(),83)&&(eKm(this),ZJm(this.Nua,function(){eKm(b)}));_.jq(this,Promise.all([this.yL(),this.KT()]))};_.D(_.X7,_.Wh);
 * _.X7.Ka=function(){return{service:{chrome:_.oB,config:_.pB,wk:_.iB,wV:_.j2,Np:_.Kv,E6a:_.Esm,ysa:_.uol,qc:_.Uv,Bd:_.Zv,c3:_.tic,K8a:_.K7,stream:_.Jv,yab:_.THm,Se:_.Hv,window:_.kv,visualViewport:_.YEm,Pz:_.L7,Z4:_.Iv,Fla:_.tF},model:{aG:_.iSb}}};_.X7.prototype.yL=function(){return _.Ch(function(a){_.hi(a)})};_.X7.prototype.KT=function(){return _.Ch(function(a){_.hi(a)})};_.X7.prototype.EB=function(){return this.zr.EB(this.getRoot().el())};
 * var fKm=function(a){a=new _.Dq(a);"Z9MBEf"!==a.rc("jsname")&&(a=_.Xu(a,"Z9MBEf").first());if(!a)throw Error("vm");return a};_.X7.prototype.JZa=function(a){var b=this.gJ,c=a.data.Xk(),d=this.hE();a=a.data.Vk();_.XVc(b,c,d,a)};
 * _.X7.prototype.pyc=function(a){var b=this,c,d,e,f,g,k,l,n,q,t,v,x,A,E,H,L,S,W,Z,ma,pa,wa,Ca;return _.Ch(function(Ia){switch(Ia.oa){case 1:c=a.data;if(c.Na)return Ia.return();d=c.Aa;e=c.Ia;if(d)return(v=c.Fa())&&XJm(b.wk,v,b.getRoot().Bb()),b.wga.reset(),Ia.yield(gKm(b,c),14);if(c.oa&&c.Kt)return Ia.yield(b.DGb(),10);_.HFm(b.Jh);c.wd&&_.Vv(b.Jb,{wd:c.wd});f=_.tIm(b.uKa,c.Ma);g=null;if(f){var Da=b.wga,Ma=f.el();Da.oa=Ma;g=_.Rh(f.el(),f.el(),"sTFXNd")[0]}if(!b.ZD){Ia.Hb(6);break}_.Dh(Ia,7);return Ia.yield(b.qFa(b.ZD,
 * c.Ma,c.hLa),9);case 9:_.ji(Ia,8);break;case 7:_.Eh(Ia);case 8:_.Fj(b.ZD),b.ZD=null,b.WTa=null;case 6:b.fD.Gk();g&&_.hu(b.Ym.oa())&&g.focus();Ia.Hb(0);break;case 10:return(k=c.Fa())&&XJm(b.wk,k,b.getRoot().Bb()),b.wga.reset(),Ia.yield(_.$Em(b.vp,c.Kt),11);case 11:l=_.Efc(b.vp,c.Kt,c.oa);if(!l.callback){_.mb(Error("wm`"+c.Kt+"`"+c.oa));Ia.Hb(0);break}n=l.callback.HJ();b.Jh.rb(l.callback);return Ia.yield(hKm(b,b.cJ.Xi().getQuery()||"",c.oa,"vhid",{Xa:n,Xd:null==(q=n.Db())?void 0:_.ug(q,_.tg),Ah:l.callback,
 * oKa:l.stream.kx()},c),13);case 13:b.Jh.mb(b.getRoot().el().querySelector("[jsname=CGzTgf]"));b.Jh.wb();(t=b.vp.streams.get(c.Kt))&&"regis"===t.kx()&&_.zh.broadcast(b.document,_.Dhl,t.Gd());Ia.Hb(0);break;case 14:x=Ia.Aa;if(!x.match){A="Viewer";b.Se.Noa()?A="Standalone Viewer":_.Sg((0,_.iu)(),117)&&(A="IU Viewer");H=(null==(E=x.scope)?void 0:E.zn().getType())||null;_.mb(Error("xm`"+A+"`"+d+"`"+e+"`"+H));Ia.Hb(0);break}L=x;S=L.scope;Z=W=L.match;ma=Z.Es;pa=Z.result;wa=void 0;if(null==(Ca=pa.Xd())?0:
 * Ca.hasExtension(_.Idb))wa=_.w(_.ug(pa.Xd(),_.Idb),_.tt,1);b.Jh.rb(wa);return Ia.yield(hKm(b,b.cJ.Xi().getQuery()||"",e||d,e?"imgdii":"imgrc",{Xa:pa.Tm(),YF:c.YF||ma.id(),LPc:x,Xd:pa.Xd(),oKa:S.id,Ah:wa},c),16);case 16:b.Jh.mb(b.getRoot().el().querySelector("[jsname=CGzTgf]")),b.Jh.wb(),_.hi(Ia)}})};_.X7.prototype.DGb=function(){return Promise.resolve()};
 * var gKm=function(a,b){var c,d;return _.Ch(function(e){if(1==e.oa)return e.yield(a.dea(b),2);c=e.Aa;d=b.Ia||b.Aa;var f=e.return,g,k,l=null!=(k=null==c?void 0:null==(g=c.oa)?void 0:_.nSb(g,d))?k:null;return f.call(e,{scope:c,match:l})})};_.X7.prototype.dea=function(a){return a.Ia?(a=this.MB.dea(a.Aa,a.Ua||""))?Promise.resolve(a):Promise.resolve(null):WJm(this.MB)};_.X7.prototype.hE=function(){var a=this.EB().width;var b=(_.hu(this.Ym.oa())?0:16)-32;return a+b};
 * var hKm=function(a,b,c,d,e,f){var g,k,l,n,q,t,v,x,A,E,H,L,S,W,Z,ma,pa;return _.Ch(function(wa){switch(wa.oa){case 1:return wa.yield(_.Jna(_.Iib,void 0,a.Ci()),2);case 2:return g=wa.Aa,k=a.cJ.Xi(),v=null!=(t=null==(l=e)?void 0:null==(n=l.Ah)?void 0:null==(q=n.Xk())?void 0:_.Ws(q))?t:0,x=a.Hd.Md(function(){return g.render({query:b,ARc:c,cAc:d,oKa:e.oKa,YF:e.YF,FT:k,k_:!e.LPc,pF:v})},{yd:f.yd||void 0,BK:_.fIm()}),wa.yield(aKm(a.Aab,{Xa:e.Xa,A3:a.hE(),Ah:e.Ah,isActive:!0,ambientParams:_.QIm()},{wd:f.wd||
 * void 0,yd:f.yd||void 0,Jr:_.iIm(f.Jr,5),BK:_.fIm()}),3);case 3:A=wa.Aa;if(E=f.OGa?A.querySelector("[jsname=rucRD]"):null)E.style.visibility="hidden";x.querySelector("[jsname=CGzTgf]").appendChild(A);H=a.getRoot().Bb();H.appendChild(x);if(L=f.Fa())YJm(a.wk,L),a.wk.oa.has(L),_.qIm(a.wk,L,x);_.hu(a.Ym.oa())&&a.ZD&&_.cp(a.ZD,"display","none");return wa.yield(iKm(a,fKm(x)),4);case 4:return S=wa.Aa,null==(W=S)||dKm(W,{element:f.Qp}),a.WTa=null!=(pa=null==(Z=e.Xd)?void 0:null==(ma=Z.Gc())?void 0:_.w(ma,
 * _.$gl,24))?pa:null,a.document.dispatchEvent(new CustomEvent("viewerOpened")),wa.yield(a.xna(x,L,A,E),5);case 5:_.Fj(a.ZD),a.ZD=x,a.Jh.j0(),_.hi(wa)}})};_.X7.prototype.handleResize=function(a){jKm(this,a)};
 * var eKm=function(a){if(a.getRoot().getData("bp").uc()){var b=_.$d(a.getRoot().getData("bp"),0),c=a.Nua,d,e,f=null!=(e=null==(d=c.window.visualViewport)?void 0:d.scale)?e:c.oa();b/=Math.round(100*f)/100;a.getRoot().setStyle({top:b+"px",height:"calc(100% - "+(24+b)+"px)"})}_.pp(a.getRoot().el())&&0>$Jm(a.Nua)&&(b=Math.abs($Jm(a.Nua)),a.getRoot().setStyle({left:4+b+"px"}))};_.X7.prototype.e5=function(a){jKm(this,a)};_.X7.prototype.Yxb=function(){return this.ZD?iKm(this,fKm(this.ZD)):Promise.resolve(null)};
 * var iKm=function(a,b){return _.Ch(function(c){return 1==c.oa?c.yield(_.bu(a,b.el()),2):c.return(c.Aa)})};_.h=_.X7.prototype;
 * _.h.xna=function(a,b,c,d){var e=this,f,g,k,l;return _.Ch(function(n){switch(n.oa){case 1:return n.yield(iKm(e,fKm(a)),2);case 2:f=n.Aa;if(!f)return g=Error("ym"),_.mb(g),n.return();e.fD.lj();if(d){_.zh.broadcast(c,_.dSb);d.style.visibility="visible";f.FW.Bb().style.visibility="visible";if(null==(k=f.w9)?0:null==(l=k.Bb())?0:l.style)f.w9.Bb().style.visibility="visible";n.Hb(3);break}return n.yield(bKm(f,e.WTa),3);case 3:return f.lia(),e.aKa(),_.yIm(e.fD,!1),n.yield(e.wFa(),5);case 5:if(b){var q=e.wk,
 * t=q.oa.get(b),v;null==t||null==(v=t.Vf)||null==v.Aa.startTime||(null==t?0:t.Za)?q.oa.delete(b):((null==t?0:t.Ma)?(q=_.mgc(t.Vf,"uvphcdt"))&&_.gB(t.Vf,"uvphct",q):_.hB(t.Vf,"uvphct"),t.Za=!0,t.Na.resolve())}return n.yield(f.qGb(),0)}})};
 * _.h.qFa=function(a,b,c){c=void 0===c?!1:c;var d=this,e,f,g;return _.Ch(function(k){switch(k.oa){case 1:return _.yIm(d.fD,!0),d.fD.Gk(),k.yield(iKm(d,fKm(a)),2);case 2:e=k.Aa;if(!e)return f=Error("zm"),_.mb(f),k.return();_.$Im||d.fD.Aa(b);_.zh.broadcast(d.document,_.Idj,!1);d.document.dispatchEvent(new CustomEvent("viewerClosed"));return c?k.yield(e.QDb(),4):k.yield(cKm(e),4);case 4:return null==(g=e)||dKm(g,{element:null}),k.yield(d.rFa(),7);case 7:_.zp(window,"attn_viewer_close",null),_.hi(k)}})};
 * _.h.wFa=function(){return Promise.resolve()};_.h.rFa=function(){return Promise.resolve()};_.h.tna=function(a){jKm(this,a)};var jKm=function(a,b){(a=a.ZD)&&_.zh.broadcast(a,b.type,b.data)};_.X7.prototype.Osa=function(){};_.X7.prototype.aKa=function(){};_.U(_.X7.prototype,"fJBVee",function(){return this.aKa});_.U(_.X7.prototype,"zfeGSe",function(){return this.tna});_.U(_.X7.prototype,"o1YwPc",function(){return this.rFa});_.U(_.X7.prototype,"H11Ahd",function(){return this.wFa});
 * _.U(_.X7.prototype,"e73z6",function(){return this.Yxb});_.U(_.X7.prototype,"onf9S",function(){return this.e5});_.U(_.X7.prototype,"mhSdVe",function(){return this.handleResize});_.U(_.X7.prototype,"zQYYb",function(){return this.pyc});_.U(_.X7.prototype,"C6KsF",function(){return this.JZa});_.U(_.X7.prototype,"IaQd1e",function(){return this.KT});_.U(_.X7.prototype,"npAYtf",function(){return this.yL});_.ev(_.Kib,_.X7);
 * 
 * _.X7.prototype.yL=function(){var a=this,b,c,d,e,f;return _.Ch(function(g){if(1==g.oa)return b=a,c=_.ze(_.T4a,a.Ci()),g.yield(_.ze(_.S4a,a.Ci()),2);if(3!=g.oa)return d=g.Aa,g.yield(c,3);e=g.Aa;f=b.getRoot();b.oY=d.create(b.window,e,f);_.hi(g)})};_.U(_.X7.prototype,"npAYtf",function(){return this.yL});_.X7.prototype.handleResize=function(){};_.U(_.X7.prototype,"mhSdVe",function(){return this.handleResize});_.X7.prototype.Osa=function(a){this.oY.Osa(a)};
 * _.X7.prototype.e5=function(){this.oY?this.oY.e5():_.VJm(this.window,this.getRoot());var a;null==(a=this.Jh)||a.j0()};_.U(_.X7.prototype,"onf9S",function(){return this.e5});_.X7.prototype.wFa=function(){if(this.oY)return this.oY.xna();this.getRoot().setStyle("display","block");return Promise.resolve()};_.U(_.X7.prototype,"H11Ahd",function(){return this.wFa});_.X7.prototype.rFa=function(){if(this.oY)return this.oY.qFa();this.getRoot().setStyle("display","none");return Promise.resolve()};
 * _.U(_.X7.prototype,"o1YwPc",function(){return this.rFa});_.X7.prototype.tna=function(){this.oY.tna()};_.U(_.X7.prototype,"zfeGSe",function(){return this.tna});
 * _.X7.prototype.DGb=function(){var a=this,b,c;return _.Ch(function(d){switch(d.oa){case 1:return _.Dh(d,2),d.yield(a.Yxb(),4);case 4:return b=d.Aa,d.yield(null==(c=b)?void 0:c.Yua(),5);case 5:_.ji(d,0);break;case 2:_.Eh(d),_.hi(d)}})};
 * _.p();
 * });
 * // Google Inc @.get new metadata.Google.Inc!
 * [mozRequestFullScreen.data.Google!
 * ]